[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f73a49684d125374ea00972670ea11e9497e21a8"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "213ff45ffb0e904a6334d112b37a4e82d498c1d667966055157be9c8a28f064e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2fd8b4a897b72f3a06f3be8f3207d62f2508458"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "77115c8d66f1c2600dec0349115a1f06fb08a25b52c853b390b7518f5643743d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b87732d9c98ad904e9040825bba40ab41bbde91"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "508a6cd2028fdcbbd98019ffcd05f93ee83ebd5a1330b4aa7e5cfd8f8547910f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e75058643c85c70842469f3d4ef337dca10452ef"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5b006b1d2151054bf6a0a985722ec7e1e8f5585202ab8a243a46732bf6c4e68a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b5c32164e993828db52b5f14d6572dc4e25446ad"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6a785d41ff4df9f4be5483d558b8f502698fff307fcca353100824fcd8055812"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72eaf56198cdccd519452fb3f741ae77829833d1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "939321a7c35098d5229e0060b5bd9003c97b967a9e25aa33035292d9af7761c7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c994c18e7480caa420588e54587d042255f7cb9c"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "29e01b6477802f240217478cd64583b755cbd1a9ae96cfc2f891b4666dff663d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55280409a2ebce3389c78301536dce1483df9d05"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8d1c7660d0f1c4eac2639ee4e6f2efe6d861edd709604c372fce7a5305ea47b8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f1c095c82d0e30f542652f219c7c1b1d025b92c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c06697e176d7633be0506fdda12cbaec546ce4e92420105617f41d11998d5180"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d1414fbe6adcc7270667be3849464e38bc8787d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "06eb198f37b5b7693f90d2fcceec2d66d8ddba31929afd822680ca89aa081d42"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "961d453eeef5c7957c3cf44c561fe9783f2396c7"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "b24bd12d1d095c624315ebb6210249d32950f87af3136ea3ae83b9d571d44596"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "383ded586b9d8c3ff3a2ae640bf53ba8a6e2d106"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "83900b23a63652504a400bcc51d94f12df3a8d99dc0b90fda6cbb1ef9edaa457"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e1d7517bf9264b62bfda19d3deec2c9bd20bfaf"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9caa7f94151e4c78664ba58a0c2715ef354f47aebd046993ad719c2e27bd7363"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0361ca4d2a17d9de42fa1bf6cff7ab51fc15137"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d1663b03c3be45b8466a18c27a8f973659e0b14f2f5123c3e7422ba5387d9751"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "303267939f8dbc4f29f3c28f6589d5c8f0502cfe"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "020b2cf8a9263263364b57b03285aa71a7501b5cc44eb1cde3858eb27b63eead"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "78c3056db2078d65d99d0cd241a26796145dcb43"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "de7a00cea7e993178da94f74fb247ddaa2d9d21fb58b4fd5ad2d9c825d41fc32"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.8.3+0/libsingular_julia.v0.8.3.x86_64-unknown-freebsd.tar.gz"
