[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e99a773a5a12cd50991f69d46b0c2878e869471"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a5fd11059f913dfee4b540de37309ff083f3bce3fb066abfc217963cf99fbfdf"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd07d1b4f2fd76f3604a172c5fef4127062b569f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "346a37baeec68ab57379bff1eb8a2a9bce87a61f219772a948a0e1e1e97ef09d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6b86cf0a9e6c162df41b2b929fd2f51d9592390"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0bd5e84398567c256cbe8d38fba0a0e4486679271e2ba8d521e3f5caddcac48a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4b9222598f2f7adfd1cfd8ff8a91487cb615d10"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "65faf5785c6280419e7c7b67cd60e0ed992b407c890efbace420bfca3989230a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6be5fa435c3841ebd7e7cf5ddaf6e23b94ddd1f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ed842ad474ed163d487ef85699d04a38251e85cd6fab3f4dc93c5d32a6b65145"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f4291f6f3f57356e3955194e9a299848b81fb4b"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a08c30aaaf4ac04eb6b7765db292f7c3020586908a4f3a8f310f913755eecda6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f38ff27aebdb04160f4664ee6edb5da3a7912de"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e98b3e34b56b41fa7c6faa0cc626173be97d46e42eab71e5bd3beff27b13b8c6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29facb5a69d5b099d29980638e5efdd7b7f75125"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0b707db64bdadcb848e542fd21e38fd4409041fe8e1f7320ba68fd643018bc4b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2b23ab9fe1c4698c6b3ce45bf13222900c2a954"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2ea717fbd35a64d0ba3bf52e0a4cbbd1babedd9238beb65d69edc360642ff31f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cfa7d35ab3e014aa93ad12995da111a7e3c4d5f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "87f70a4258fb478ef66009532769c64f616ee3fea2cfb198548118461abb83c1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "443c8c53744050bece56724819a2790ebeb01449"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "5e3f77fffbcabd8df8b304949d6adc71402dad5b8eb1fab41785199f167033ad"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b96a9b7091acfc05714d200ea4cb52a6cd18289"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "66d5baad9f3c5e17fd56f92ffc2cdd615dc3b2aa3b4ddc650ae8b2155db8baf7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d86e58080459a4a34f9212a69bd0243261404b09"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "87d15b168ddf5e119a08424836c09a5eb9caec2bb98abfcd6213bb79e6f3d85e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a5f0bb6994b37404b4212de1af14f4a55d0461d"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1e620253bf37d3f2c63acf46df15f5eee31c00fd0383034ae0b4d6a5d1614249"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6e455254e01298b2be7e36785afa29dcf758b35"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0b6ce624e02353da94af60d7e594f9c1a34221f0ca1efcff22afdc50dfeea6db"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "26286f8f58bcbbd42f7aee5fa19a99c9617374d5"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "4e74020e6b649c8d868d2c5b294f6dc32dc8a7c34e807087039ad6f296c9f073"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.3+0/libsingular_julia.v0.15.3.x86_64-unknown-freebsd.tar.gz"
