[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b54e22cfd2d7b4a7def89f54069291ce99c36f9"
julia_version = "1.3.1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0f225f5f334fe88b50e32a925bda6b3b496a3e11e6505ab12da5cd2a2efe5781"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.aarch64-linux-gnu-cxx03-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58d996fb39273e4b993ef8707314ccba8c995493"
julia_version = "1.3.1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "191afd37f8b40d15d21d67567e59235a5f09db15eb273e2af6ad2a1ee5955e14"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.aarch64-linux-gnu-cxx11-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc7923d0c57489f0e26bdb9fd4629042b8691c32"
julia_version = "1.3.1"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8e68c9b0564c007200a3553c43fc271bac8955160125fc34489d697067b15f9a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.aarch64-linux-musl-cxx03-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "211bb31970c688d809fe53cfe288ee1de4c848b6"
julia_version = "1.3.1"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "10bb975b30588ef04c34d34bf7f681043ad5a76bb4cc546d31f45a9547cfdf05"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.aarch64-linux-musl-cxx11-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ccada77e9bb3517400f1f969ff7c76cecd044d9"
julia_version = "1.3.1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6dcc57952b885f358addbfe933b60d90861a802ab7707695aef2aec3fbc9162f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.armv7l-linux-gnueabihf-cxx03-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b936c60775ebad5969e1a94563a903e45ddeace6"
julia_version = "1.3.1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ff1b551038035b05673ac0ad25afe7f6077686553152d8b96abf5a3c5b6d560c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.armv7l-linux-gnueabihf-cxx11-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b8d9d2e0106c8ccf94b86ed4b9b684ae6234515"
julia_version = "1.3.1"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "603242df24c8864fe694e4d048b6d7f7862329b1f93a5e9af7e80739d9ab61de"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.armv7l-linux-musleabihf-cxx03-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "228ee24167bab4b4a772ea1b513b70673b50ccc1"
julia_version = "1.3.1"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f4550c0e568d478f8863026059249dd1955b413a430c67ba417f3707485d8639"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.armv7l-linux-musleabihf-cxx11-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba93931658679d2b441b786218d6f8a40e85b74d"
julia_version = "1.3.1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d555321373644e5c84b2bb54f9ccdb794a0a0a7102546b131b0c11e3c1bdd0b6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.i686-linux-gnu-cxx03-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e340fa915a991b8dcbe54393fbbc0206f8ea5095"
julia_version = "1.3.1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "09d324dffa5278b5ea8f1b5e28da50396c648b9fc5cadb359f6826bb570a86c0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.i686-linux-gnu-cxx11-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "c1f8bbca32a8a25c1b90da00d6c37dff11021d7a"
julia_version = "1.3.1"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "5991f2c0525661cf5fd3a5a38bd01937c37bc54cfedfe6f99f6d47b4cff72312"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.x86_64-apple-darwin-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e43dbeb2665d27c179170f4b867900685e24216"
julia_version = "1.3.1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7fa1c9932a166c6b737cb41c30791e9a10fceecfc618d36d2882bfb13e1bd6f7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.x86_64-linux-gnu-cxx03-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56e58474320ff8018bb49fbbc8f343578f5378b8"
julia_version = "1.3.1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d6ec4ceca11f93dd6dfc596818c3c7a0441830fca92b80b566edaac9f5afe806"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.x86_64-linux-gnu-cxx11-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5db9b53569ba1ec60b7c85944366bb402d876038"
julia_version = "1.3.1"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0af1e6349685b0c702bfac1ab2c3d6e172c6bdb80315dbd20f06732b665a4764"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.x86_64-linux-musl-cxx03-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cb070ec22f8914236e14704b27f62ace757d1f2"
julia_version = "1.3.1"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2b1539e12269a417677033432cd93d6c9b2b717a5891812728e1a80f94a29679"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.x86_64-linux-musl-cxx11-julia_version+1.3.1.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "8e9b771fc354b05ef07eefd0679331e1dbe6ff29"
julia_version = "1.3.1"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "a3ed8ad056bf7b1764c947dde932630a1bd5bfdbef93d8c134a8d9dc844d8c91"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+0/libsingular_julia.v0.18.3.x86_64-unknown-freebsd-julia_version+1.3.1.tar.gz"
