[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bce42a169e5ee52bd97206bd6ea45c53eab2f95a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7e71e224d91daa3106fc2606f83c2e34f8b5524ccf8eaa25c575547895a93d61"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f817210b556c2d9390ee98b990db70f4fb2d2ccb"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8aaa15d76676d045ff4d2296330a6bc3d7897bf23e49b5be11c5c1170981047f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8445fbcacbd4adcaf0f8eef18eff0fde8930f61b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3f0c77a8de51fd08928af49d99ab81bc3c69182b52e16d070b8723d4a3c7d5a3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1b4397190c25dabce10f6ec20ea562344f8b23f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0e434e4cfb8323f69187360213a03cf8ab5712aea3801fdf1fa0ab6ede5702eb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0f6b54acbc2bef4def441b961998884e7851ffa"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d194bb308873992a7bdee7482fe80da6c545c2bc8d1ab3d5e3577bdacd5affcf"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "818c75963e77ca99a8207848672ad947eae4f2b8"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7625f649128444a345e6803d8ceb44b214561b894a73519f755b79cc50e29869"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5881d6c06070b64d9a318baad5fffad19f1c27ec"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fe0aec5a8ffd0f576f47ae3013dfae6c7f94c50cb909b0d72d123f1e854fbdc8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f1e0cd7982d55970d18fed011f08a3b7dbffc0b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a387977970f49bd3a38c40f5e92d69f0bb7490a2038469ec7b2a7768521a14d2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "707478baff45698fd524a6d05a15cf292fecbf78"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9fdc1864573af25f51c7d6cb7c2061ed1ea6a8c6b4b2c9fbac15bf1a8ce7fd3f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83e27b58afe5a6814c9b86672ca2337fbc1c3fd7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a816fe9f718a3a4fe78e1b061914a5f636288cd1185ac385b6a0f9398c792265"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "756515d1e6ef53064b569ecd7cae5d2f3c341672"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "751ecc3c54eb59ac08bd1b7be667692244cd79b44c57ba2c5db886c6797771b0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e50278eacb751c697f1b0601bab13ebe7c2c72bc"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fb14cf7dada8195d1e55c5830304b4b5aa1841e7c25efe551b1378c67aa1239b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d015b4fb02fe1c8d7603163d64313ce918607a76"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "bf7d1012887465f02e01c234e3add15b14328062d5ff79a53d9b1a9d6ca43c16"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d531f09f9fc657823cbd012be5fbf893e9d1a708"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "82d44fa0c31ea33490b0c90c5e140dc64d298ebc9cb1b3ddc9061cc6aee9574d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7b2b060564ab9ca8cace70098167f91b7371506"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3a31cbb640a46e3a4a102adffc443bf777333ae39e1cdb37b8237dcc4434176c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "224f6c2573e22308d0f85e78b20c9969052b078f"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "fd05890cabde5225c74a8cb609a9463f34fa85cfebd1b4de0acae51ef731c14a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.3+0/libsingular_julia.v0.11.3.x86_64-unknown-freebsd.tar.gz"
