[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "396fc8a4ac6b7dafba04de39ed660241487088a6"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "91000c9cadc088271c3c591f65d4747007fbd51a6f3d56f1c9959bace1dd7040"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc705009ac421503bcf887376cdec08b84e0ee1b"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "213a06df8d87ee45c65c92bda00e6eb0a12840d90fbcc7c1bfc6ff255607d3c8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c20315899e144cde1c2ae6d0b5f9d1609c516ab"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a7dc9569cdfb11da4fc8e1c751f1ddac22a3412a539f4715664bdea32c388e64"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc611bb3b1142ab38066dd9410f950469260a482"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e6e555e7f513a119104d6493b90bd975897ddbfc587eee4306e0d10d53655903"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d3971042c1885229465c2d3be71193a953b297d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "70d2af6f84332b653fc69112ecb9b91ec73755dc9740e2b402f72319f252929b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a10cc54926403252a60940f3fedb3f619164b8d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "da414cbac5ff980850217806b2cf62fdb820c0e7ca77d057c1258af29e019ff9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccb26cf022ab0b7b60b2cfb31e57cf1bee00b1fd"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f3932d82b94163a1289d19afcc9042fb5bfb11f0ff1bf3d7d11caf24c3f1ce49"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52b7390fd53787aba9def4d28b2334ecdf433f3c"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4a35b50885f4c7c31cb5c0ca648020ed98240dd4ea8470cff5ab3e0e7cbcd950"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4184ba694561699042faf2b3be1b74d7a93ab2f4"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "faf04efc1d116b74ff2805744a460634ce54a85919ad50d3147a163eba3cde45"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55f5b8364525d9e63c7f6eeabe787542d9d60aa5"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0a3c7b96a996fef4d8a63f7fc708f146c2d74c1fc7615fcc44f3ea0763794fc9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "039ac3144213511d9ccdec4dbee93201ea1b804e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "dd7377efaac0c304f76bbc3bb497a34029530a7803788b4039effa0a379c5fcd"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae406ef5dae7b553b00851e1d01ad95259be477d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e3cc0c780ff02574bb503f7691ea9ec66f6a4218632f16d72b9dc84775650844"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "60982a979059372b32f1d1d5eacd6e0cd66eae89"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "9903e8123a08d58aebf5aeb9de1e792c53c8eb3a1c77fc8d9d5589bb5be8d50a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac36075e5c76d852900f0d0c9cab1be4bdf468de"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "956e5bc87c4b6bb00ea47933b93b0e240f9af644db21c01e461068b9d102fd80"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3de560e9b36d9e4ce77f914d678b52e9aa5f08c5"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "400ea117f784bdfcc061dc816082a4995a5436d51e2e604ca171c45afb64e0fb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d8745b357c5fb497bbd6bebf49b63bd24823e0c"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5362309b27fc101484792c778e9b2e6d01aabe214ae427250d29970ac9155d04"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4e151cbf046bef99fba264808f1901a7a6fa902"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "520db35bdc972a3b6844ab0b471e3752356bf13ffd4579e7e493f167ba42963d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "90f74f83cc95cc66815f5174855f1a9938531465"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "d0fc9e0446e2433699a4f61ea35e19f5106aee9845bcd4cfc18d105e5c1765a3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.11.5+0/libsingular_julia.v0.11.5.x86_64-unknown-freebsd.tar.gz"
