[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af10347c85ec0ffb32e4ef436e1d440273ee067c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ffa6b59f529ff3854a0edfffffde5ca850d367060cfc7834b56fb2eb7856190f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6aefbe098cda87b661047afa0e17dd8e473a6209"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9e1862722cc8b11532db3ca4ac8c810601e5a675ac19510235e9714457661380"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4712037b30e9c05a8b93d2c239dc468d3654edff"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e052f774656f7623e7acd303f86ff0c691edb13c59ed78d14ccf6f0fc9302f4d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fa123d477aa44bc2be9968836c2ad3a46a0dd5c"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "61c466f8ee336a0a36cca8efc0b4dbef7d50634d6a57314e7fc261223c509993"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38836ca833844cdefe0bd0993a927f2684c9a7a7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "384766295ac0501066ef5208e80c589a0606150983e360503d53850c1b42d93e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95effcba0b44686a8a3d7f8c9299fbf8c7411d9f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b70963a56085c4d0b9c335cd2d275be18f07b53d4b6ffd9100cf6df06d07233c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0aa9db1bbf9037e499916769454ec075daeb4c4d"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d306449b15e1d804a0b3db73b907dd38c7a4f6691d63f4271ddfe1b401015647"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8a1e4bbcbb5c7af07f785d3777b145e6bce876d"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1c303a28a8efea7ac86f3194c9dd6be0e7566dc59ac5c220478074de5773ed19"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a062a3169461ca52a67f80adc0cbaa5642ca753"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "877befe7848f02b0e99ab2c924b997098e55b5b53ad34927f206b5b935eacef2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b4f5781c14273f42b577948c80e72a6ea5426cf"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "206fde75f1c88836fa8516d2b97bfe7821487adb626d2f55c4512feb3be9b005"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e0b730dd787e47234eb0dbb45b82123979b9d85"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "33d3abfcac9cf39037731f9362388eadc7973f301c4de35fc80cf854b542bebb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e96024d09a5a2e98baf9754c081bf47d1132b77e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ad7e6cc33c878facff3601d05cf58601446223251cf5a1d048ccb2b83195c534"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "31ad9ebda40e3499dc3f1518aa4780a4ef888ebe"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "4eca14077fde1f0b509efce214628a5d6761346382fc0c8a5d41eea06bb35f18"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85bab9f157801aa9b122563aed99b9f957c6f30a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2e70ce5d4a39b5a05a0074315a664da0e79cdd8cfadfd39a6d41f81226a778f1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acf9843087df4c3e1a35e5aa641015604a5e8e43"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "54171f909ea99c9565861c68611a7e47e552e49519d072ffc490cb2d53e6cbcf"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c1754bd1be15c7c36d126bbe19cb04054e0e7e2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "cc121c0fd99ffdaffb1933bd79635770b13e74244a0f9ff173166cb3ef872ee2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65434750ddcd681408b4d552a9d5703ae1fc058d"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f0ff8f755db5746a38294ef922c03e10de7906e01f0558cfba980dc7301eca40"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "a27aad8f2d39705ad54f45268d5d58f4c74296bd"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "a458bc6144fda44a4de66d3228f4f61fbaa8de2eb9546551a564f2eeeb64af9f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.4+0/libsingular_julia.v0.16.4.x86_64-unknown-freebsd.tar.gz"
