[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ece5a6234d8e442067bbc20480b576a344dea685"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f77138e62980ec8c856469c1235c8b16cf9a23372e9ecaf013a070d655ed7aaf"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4122cfaacfcc4fb41e4d5b7a3a4194b047087608"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a62a99ac38e9b75131fc61ee54cc4d3cf48b8009ccd3face06dea067aa07cfe7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2983beb8a3214174462f4097faac302bcbc48a33"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "81a7802585ebb9856800eaaa0387aeafcb886864583c55875f72e4568573d6bc"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "292a7ddeb7f1bf5da93663d514e97ccd5d5be8f2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "86bfbc0bfd246524cc855b035dfff334810d4b8ca92b19e5cc49d29e1cd6d78d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29ee7a1fbd9e25d2746e1af460e9e6124cd26b88"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2328f0d0b98424dd552078dd6fa32bf48bce72ba0eb551cfd2d68d47a9fed8c0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b057b3f9229f45969f26d68d731078e56365f90b"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "959a4181edf9bb9e9d9c686a2fdbb25c5085142cb6ec54c0b63d3c3e7216a1c2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b67cf2713d154851273886d9c244697bacb6bfbb"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "74bf2c1627f46d75282177615585f8a65ada5ea2e69b0899df456ccbb663be7c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f3870191e325eba12b5946e09215b22153959be"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d26e1fdcdb85fdcc2f54e4c90719f9fec8fbe208db8853c29ab05f6d2b6dc43d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ea8d1a8a1ff80be384cd14ff736b8e4d3ff3a92"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "bdefe17026e5d15c20681015384f34256ab7e0a3c280d4f925986bebbc95a845"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21c3cd4faa036cca4931a4dc729a21f1c066f853"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9b9e623d47b79f70390795309aa0fc2a9780a7ccaf3233ebe1c392a79916ca77"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "afa66c29ab57e0e71a7a2781d9e47d15a0fbaa83"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "681a3d4609032d988c648c7c4fbced3106f8dc53f773f2fe5ef0dada28917d06"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53649a76e82157519dcafc74874e4c1b8e6b47c7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "be71a936245397eac2d2ad45ec681db83167b838192ab61ca87f5a8f7f5aa5c5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8ec64181a6966ace3a7c991dac89f9ebb641b60"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3cff733d4e9e9daf87f70da4a71795ceacc65763bea3abcc837d589fd13d29b9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ceeb0afe8086bb3ed9652e8123b5fed02cdd566f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "db63cfb0686b31f63f9221259dd380271969a2cd698557a97b963f5fab37799f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ec12b9a8df7afc87f131c1b1705de657268a37b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d9cf8dcfdb1e455f6e5263938ac5282aad2424984449fb86d9eaa19ec9744498"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "e16b397d770bd0dd5b1a715c12aafc174980352f"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "eac0bebcf6083d2514cf3ff1b57868c195d8b239c32ff346ef7dec06cdee309f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.3+0/libsingular_julia.v0.4.3.x86_64-unknown-freebsd.tar.gz"
