[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e50ee5a143f5b4f0ed4a6a6a2d45891d3421b18"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2715185df6ba443cf1733c1028ebf46b526e724cc020b9da11162310eba29e93"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea65d74d4a5a99a0235886e8f9eed9c5f0fb1044"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5e1c34566fb8be8dbd3922ccf27ef6ce7c4de22557c368cc3806637cb2928674"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d35a9b8453fcad5df310785acc6015fa44b0a7b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b1e663f3fc919c11b8bc0f1877474eaf0ababe7822ceaf29a238958832c2e296"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c21e06e443877d34ca8822c674129eb0b924aed3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3e7b1d4f51ddbc7a2a22976c67e3b3bf615abf7baeb549d733424cea5f9b228b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d326af846bd38fe7ee652cc66ddcd65266d05d2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5e3156af5ce7d66b84ee25d3e731fb108fa75f3d94263367f0156b901305999e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f49319ce0cd32118c08b73a5ba1974c2b719408"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "69628cdf11423df68eda0d809e13601540ee80bb61fafa59d3c8d054f1b565c1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91bf8d765cd0bdc301db24581ef2898e90156ce9"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e109e5030c2ce2ea42874725de4b838df5da05e75647201ec93655e3126b563d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bc875e855957cec264eca9e2c3c16f7c44df50f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c39900dde1532baf06e9444ba2011ea8ee1235599b8a3895053062ec06547cdc"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7daa4ddbf387dad4ca0a235fd73914e7f9fbb96c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0c4184f610dc5df381da31350a1885ecd32bee44c2a001070d720346025317bd"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37d10318d87a0dcf49efdaeae2480df828830f1f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "96c4d8d61c420c063b1eef03275257399a63aaf27677743c3b94609faa169115"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "c3f42bcca01759d3b43c688d04ef43eb976e8082"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "e5154581f81f607ed6951ca13a905bea10600b20def77b3c90225fb637c9c6a6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6bbadc775b4df1b9a54c7174af743d64b0e7daf"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "81f398ef01f95b76f60178ac54285d047add7ad719b600b7a6097c199752ca10"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf15e54040006a6dd79a4820d398a5ee2a62d686"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c59af71667428f49b411ff2380ce987e258a25350900ac8302ebcfa0b4672bf1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "235e820eaff26f6a7bdf5d62cdedb45efccfecd5"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a9144f710d612acf7d28436c47ae7f808ea80dbab2b0eae2e60e139d12839f66"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f10b5055bb75b01948d32e87948805b1c71a5939"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fd4f02181fc280436277a3e05d193586dcec26055ee409a7f377f4167b0d2827"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "8a0031789ef3088479514f0e58f2860edb4498f0"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "04c3b5c59baa2bb7b76e6f825a2b82355a9d2d4466e3f613f328824bbcf1842b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.3+0/libsingular_julia.v0.7.3.x86_64-unknown-freebsd.tar.gz"
