[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9c12195d50bbf8758fe5f6feda8bd340fefa873"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e92bc8c9d591384eddf87508a39b5ffcc7e57db80c7fe0b5ca93a48b5a7153a5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5e9a78af8ed17d1a3c111d775b3c5d4e6a13c0c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "cf32cc9e4af7d815be4383e3ad635c5c68b1a68d9aeced90b5c3a62c9282b305"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b244abbcefef833217fa994dd6d0304db5b346b6"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1eed477ff4cbc7b63a647564a48718aef5523bb4a5d5828830e3d137f3418335"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1c76372eb8071e8947cb565c0f251728024d583"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1461dc763cf709da9f6932e49491df2be0b14ffd66c458332a02dd0a2258dc4d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35f33c985bbe5f1b57d653e7494bf03bb4b4a5c9"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f6e7f20f12ee88b712bf9c5a4b7583456180e9c6fef456103416c88732a70b17"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccae6614c5e6ce2ae8963fb222e3594c4db1396a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "156b9e769b3826b7bf7145897a430bc0d9bd98fca5ff1d04cc2d7aee8a1f4ab7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b3604ddf4f5651183123c3892b9a027d4775c46"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "61890ca3813f96557870594aef80cddd609e30a3ff5ad6200fc14dfcac3aa55f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ad96d21b041fa611b707bdb29494f5e9a5990ea"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8add22481b64afbc9206231f5bd13805ca34c3880d50a4f56249d181734f6da1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "403ea7f0a3950cb0290fdc71decfd5bbc52ee39c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "217025ac7a3f0c05bdd8441a53e21ee9fff9147c00657b661fe771e097caddfa"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c7fbf8eaa787879be2dd10045ea5ecb88dd3595"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "84056eda2a32164765ea35921e061b38741d6820f86f9383df57dc740aa7219d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "eda7c013ee099fca78d4eb0aa2ca5aa1505366b4"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "aa6f5e788bf822efc4e789418c24af0e29dd79732184aadb111de30aae48df83"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e2f4fe3e8abc7eae77f5382154e569e7800f45c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4d29683013b13d9960d909f483708802701de2be1a55796e331ba28b1d50bca9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7d82e58494b2527f340a256240284eb11b35fd7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "aaa55229ae1fe6cde55b67399240a46eeecb1d932d4907920a9bc158657286d1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09d7733504e5315058a1f9eeb9246dca6e9f0bd8"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8fff5d1fbb7b0623e73e09216130172d08426abb72c562dba594511f1cf622b6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8fe7c758db112f6252cb9d1d328096a707668ea3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b6cfd242e9f58542eca7693b5d3f65b9716aa25014c4d52c56455d931f26aeca"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "4f52442b957ee0c213ac00fc250e7f5447aedc9d"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "6a64a21acf2946fcfd64a18fd174d8e0fc626f4c1a72c2ddfc1c7793165f6c31"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.3+0/libsingular_julia.v0.16.3.x86_64-unknown-freebsd.tar.gz"
