[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "491276e0241a7927deb5d4106acccf3be6d08c8d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0601600af0b6e310ebc19e9f0f09f9029c141958ddfff79f9a81bdddec5937a5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52073a4d25dfd1d289403dc33cf9947014b552c1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3d6a8a52255f395f3bf8728830fee27bece22f154b011d853fab60c046b59707"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19bd97c42c2f77b53dc9c016ddfd2e5ee3091660"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ef308b5da4f741378fdc209168ad416a4198fe97c72514893d2cdc115f00369c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a2b864d2af1a424c35a9807903be846e5d69d4b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9aa894d1bd819abfa19c65af1f55b8b6311ff1c9514eb18ee971624161ab9a3e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58de925d9f5b7dafbd75f537e33b4956b4e562c5"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1ac7b7275f88c4255311129eebb7787966d917be1adf938a2deed8cb16e1e1da"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cdd4025d8b4747e5b511a47a341443f103318e5"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2116c64ac30b03c532017e050b3cf5404a5d473123384ed2704add15f08a585d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4632257ea121b9ec63de86cbfcfc505a580b0fdf"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3c78bbe9b915877621e41f2936d3af12aa8a611fd16cd6f1d36cbc3d61851472"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1350a05b1c95d8a7d7d29310b5f14889f6df75a"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c2db7fd4815c12d93a4ddb35959b119502a3ed3087929743e519a54be63e9ac4"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91f555de57ae3fdf50a88b7fc9b97c31dcd1ce38"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f016ce23db5a11a1538f70879c3108d786a046c377efc712c88da5d4a25dc1e1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3740923d77a8667b118f3107ef25465528b04530"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0c77dc2c2f95e77f7483ae8015523e4cdab956bf37ab278346092f66eee2ebec"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40bf690987c53480219325fa9faab49430cf82ee"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e45fb3d18d7b70e181daf8c3c6163e64041669f208b16f177cf6af9333dc3388"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e079666b0a5b90cccab0b6269e4967728da40832"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a449c909685d6963419ff8242efe3ded1c27b2c02d8cef0b26389434d3f278a0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "ef77367945374a374421ea54970a6df567598305"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "13b09510f468cb9b6ed82a10bc6c13a567d9e5111090790a645ec596ebed60ac"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "448cdebfac9d471bc57b119c04034d246fc29d0a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2b592b40db1054f974ebf62f203ac8464941f9f9e1196648fd8194dc6053b646"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6aa35c7c184ea39f2ee685a55fdf665de513dc95"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b547a5862611f216eaa0a4a66961679ace6454d9d5f1e966f4e3e4f37840c950"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb284236c8b5a371d5bc28d90b14958b84d63ddd"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "75393d89653aa1618d8e82e7df49d30a5e004dae6925d0b4145f52c7fcb2c17f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f93d5922ca8d2d5019d8368d3e8ea62a64d661ed"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6602b3a9997ff5a998061db3900896bff9e7f118cdbbe6478de3d8bc4dbbd9a5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "62208dc63a1040b58267759fc222be9e32535b7f"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "a4e92fbe7fc3c78795f3aefbe3e9cd5ab3e5e3e93b2675dcf3f89b7f39013333"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.204+0/libsingular_julia.v0.9.204.x86_64-unknown-freebsd.tar.gz"
