[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bffccb95039dbcd3d0d001e1bc025b99d009ca29"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "427a07f05d4c1fbb00cf956085ebcd61df36e7c26a6a43271fe716cd1c7cb858"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.aarch64-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "160747a2d43614a2ba952bd28be1d0d74e7c7203"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a467dcc674f683c61004495bd3f535f7ec824c8edad7313c35446f4a8d422a78"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.aarch64-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd102eda455f8102f06c94931bc39f5a4b367a41"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "40a3b2285e34161bccbdd7dd81f0dfde8edf9eaa08f2b48e4ec909e452cba6f7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.aarch64-linux-musl-cxx03-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e515c3832c19dbba1a58bf694e6df810023c84c5"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a2a7600d78e70da55b5ae37fda1ba9e281402facad330590919a3274767554a3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.aarch64-linux-musl-cxx11-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6095675cf268a0c05cb61833f756beb5bf011fc"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3c7652b56061587fbf033e80266893125af92c82840017bf3287d862c6ef6e0c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.armv7l-linux-gnueabihf-cxx03-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3849d7e7b16e4bca573f94353606e477e4f5b3e1"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c555241fa3717692c273510190458f23d5d5efb48a8fc9d405fc1523220fb205"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.armv7l-linux-gnueabihf-cxx11-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9685028803eeed3c3bef9d68fe3675ebd9ecf952"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "48cf5e227ed141afd7698abed80b68a5e757636d9e19a1af9ee406af7632a1f4"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.armv7l-linux-musleabihf-cxx03-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "011ea8d4b2e680f707c0276991c03e52c66164d3"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c01a08807ad71fbf0d4d50605442af676241d4ef6c306568b2603d93228412d4"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.armv7l-linux-musleabihf-cxx11-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5857fc1d2e30360ed512d9f5f881d7f710aef162"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "80e3abe6670a4326f8d79a2bcdc19d5afd8ee7ac8ed53be3d222aa625b8cfe51"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.i686-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c6b2f46fe4d728d33a36307a41f8f8c3e8554ef"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f5a7d0eaaec8f94020091b382b832243a0d297e29b911d26dbd1cf137442e04e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.i686-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e852c38062b311985d1d3017d388126d8296d9c"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "37c4f57c6a0b2f0e3c86a6062aeb6c131746e113e07c14652b97258084b9a3dd"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.powerpc64le-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ab2b8a700a8253b688f6d2ad2cf97fc598cdd3c"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5f6989d5fdfe524fc9ae2219a60d7ea5a2202404a2404888ddd766680a7d480d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.powerpc64le-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "0b887b254f9e22cf63b8d1b2f906e246a80155de"
julia_version = "1.5.3"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "3ea68c57b5f9d0be71c4e7efca42ff542b28c1da8b786235c6f2cfe28d947798"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.x86_64-apple-darwin-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2783487900830a658e89d97d2f2e58bc200b0463"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "821b2aa453408c16441593ea0ae2aa93d0153affe88abe72b66a450ea925ebf1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.x86_64-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "564a80463cf56eb12cec8ca7b5e13789e81400eb"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7aa277cfd0f96f7f8241d65736dd8088f00d0fa607db46ead93603ad3b6ccf85"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.x86_64-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f1afc96cbc343bbff3dc7efc084c03ebfdc3243"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a611d5ad0b022cfcafb56fb85894f246dc9ffa19263585b2a58fcc9b9bf25f48"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.x86_64-linux-musl-cxx03-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b5ff5b9d53138b7dfb654782a76d85e8dbe1902"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b11141bbacfd3e7c991dfa13d71eb18d7bc392060c837495ea351519b691ac65"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.x86_64-linux-musl-cxx11-julia_version+1.5.3.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "25ddeb4f9e1b0e5e8a326757ab8fae7ad5fe120e"
julia_version = "1.5.3"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "ccb333530d3badf3020b9f664e3458d3a2756d2391e32df32a034ce117af97f2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+0/libsingular_julia.v0.18.5.x86_64-unknown-freebsd-julia_version+1.5.3.tar.gz"
