[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab60a0d3cd3552ab3f9c29863d679109cc43f544"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "836ec9246bd77260e541cc1d9aac74055ead241065286c27c7a4e3a868189493"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8528f96a4789dea2563fe265a8cf05b883a00760"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "82ce625a89dee14bd8ce5ea44fe28e4f3e4e72fb3213361e8c7f16f42f5ab163"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32aed354570fad683dcbef2d49a027bdfd7debef"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0f1babf2ab16ed980617c2b79de950188737859187123a97f13260fe50a8430e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a6b49c5e2142101db35e7199c2fdf96bcb36b1f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "36b821995a8496e65ac454463e12612565dd60f71e21fb8fa8a38e3a477ea76f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9440fc653fee869ee1ce7b907a72b3da366e392e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "876a4fc653613eb5ffefa0c529cd26f7d4d75afe62c77f7e9cb36e61c0e89bbb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "044038ff301ea5c082d498f631533c87520cd535"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "37e908c0758836dafc43257dc47ff2c151779f4afe399c41350d18c254bb941a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d3cb51812a9b8c7ed3b96fa0cb3ab29b9926243"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c3a38d095aaca79f35f3d1ca027df94098fda4cdf60671bf25fe9aa648727582"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce345e9951e9d26fcf114131b7a86484a8df3e88"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6fcd0842a0f385036edd3ffedaf5099f0a7034096e3df602c1dd358c4f248ba2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8850cf6c9a6f969ee0614b1a8c2be06caef8e2f0"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0e7c183b137f1dbff9a78809b5161ba6bd3b28c0b3a0db8d45009fbb81b050ba"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1e6267702a1631458cc5634ae51bacbd34818a6"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e34c2202673b8e0cf0f303f02251ef870a4aca2a742903fea3093c525b1da36e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e32d3291bf26e3f0340df23b5aa958da1a14b43"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1defc4eac6b08f247caf71f56f525932ab82c2b67de8b1b9554f6ff2260dc0c5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea7f2bb1da600c8ea1a20f1456220523bca826f3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6cfc04c21fcd176f00e42ac1ac29c617adce3d62745d340f7245d54c2ae89da6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "9167b84f73bf0a59f3b13a58c6774916458aa062"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "90a46becfe4e16101f9d40098d7ea946f8e0c0dbed49619ec6accaefe8bc31c7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97750c85d3a19ad9ddba9c08fa07c80a12ed1634"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9cbc24fa51e8f5e483f4f6c21cf21fc2b10bcaac716a91035b3e0b7d878185df"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81f6b31d8039912b94fddb67203608eb124d1437"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c2fe418077a63ad1ecf97141a85c870febb3ff6e0f9705d1230ef6d3799c10a8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "caf2acea2c9b22f8be112d901d70ec848982b9b8"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9210558dc01da9d238d5672cb4cdae6b0035e70e4b279d5252b0e94a19e66bdc"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9342357d16736544a45459f174b5ff1ca754df6"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4280428c0c6bc4e932edddd0add4780bf4e03f834d434bd9149640f86c08c9f5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "df6d92d2d2c898ee353d6d0e6f2de6235e7a3f7f"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "60d551a40a093067dd65ecaccd6e0e9d673042b113153a2eaa7a1d065731f70c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.6+0/libsingular_julia.v0.17.6.x86_64-unknown-freebsd.tar.gz"
