[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1164e25c20295272ad9269d6b94be6fddf478684"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a14f248d4f679f1a30a23fcb0a180cc66cf01b5804448697b31e7a5f246599d2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ef89f09807764f43e940fa89206c70b160c9387"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a93e2d4e9f2f598feeb3e56ff484bd8edf9d972edfde686682bcad7f1470d9b8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7eef29ab409463762d2089eae7201a76aaae6124"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8494a7cb4365ebaa92043330d472090ad75483ea1815607ce2e0800a2195c63c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "707b94a1748294a13d701031420f57a9b0b9168e"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "579c5c6f555834075f445a69fd1ecd03d66bf1114422e2c0d5987bdcdb9d81e9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f12eafc94046482c3417e43eaa3b7357faf1f26e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1b6310232601d75f381002837040d9ec28879e2bc5ee88ec945878af04f5655c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35b9becc3d9987a2220ab1b9562db7bf833eb188"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "106505cceccb586b644fb112ca00f6e8b84ad36be152836f3b08b70e0e0faffc"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "606f28f913f36d04bd7dd50d4273aa5c4f49bab9"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1fb8a54d7d23b1d9e577952368d047a24768ea14d6c145ebc43df41814edbb79"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97d3c6b47c507bb9e1fd928859632b74b3282e3e"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "831ece327994f51f385b5449892ff1e42dc0e554baff636fd3c1d5ed5204c375"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cf00a95290b31c916d5bae72d4061b1f5cb4c0c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2c09a6974153cfdaf86b7ec4d8673dab49bd31926b6642e3e316457d2dd38e12"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81997789fa8e75c995252df652b2225945a02efe"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "17683f577d22b5b49f8962a2a79008d4a01513c3aac7257d041d1b32595456bd"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "c4e6f24ba6d02f3e92fab998d40082fb5482a445"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "fbe127a6a8899f930ea91eb7975cfacc2b94b0d107d125744b434906d1ed6f1d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74b21998e19c00aa20b366775c0bb0bcf4eaf991"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ef3be2120ee63cc194505a3203435b2bd0351549f0f5b6d4005c5b8df57d6284"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ff7221125d673ece356c6b245f30445b1e43e89"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "11ebbc8a92ce7686e9e36dbec3bd9e99d85b0cfb01acf4e47dccd57e94b9eb73"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0210cb714e84f9a469f9071be9ba5fd3471af5aa"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e50d3db7d5f867e77161a7dc94120dc595dd0fb65e6a18ad581ffd3cf01f41e0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d98fa01cbe6e451aa5abddebc5fc59c4f056efcc"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d55151ccdcb204e093784c33c331607582d79239ad247aa5e49d72346b819572"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "af885e03460e8e81fe5764e09e94a2a88775dd39"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "3e22419010bef55465ce7a1fffefef62e2a513b98b234b9b8beff2e583e0fb85"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.3+1/libsingular_julia.v0.18.3.x86_64-unknown-freebsd.tar.gz"
