[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67ec07aad1b8360312aa2bd9418b69db218ea42d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e478fbcb4051818874a389c5f9645183bec6ff18ea9134219c7062041538a17e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a82bfa81d3bfd8b10265eb5c5b03f82cdd2aadc0"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0379cab22ba3be95db2a0deec3f484b9de8184fe41ab4b51fe2355714ec3f097"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f49afb6838f84612677075ec016580d8c9b601d"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9be43a18d7b41bfb15cae23e7f09e828bbc080fbc057144ed7957dbfe7c7ee9b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "154e2b2d83257b99fca523978b3ced61ac881c39"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e205970cbbd85c40934f9e6b8cd2f74ca7835b1afdd83a2d123dbca8d7385f76"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cf787d1ea8ff6ffb88fa03258cec36640cd96f9"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0af659498b116fb2cafae0c69d9ddd82ef452816e7f1f750a4d3823e45173a85"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "102faefefea6fdf765154af2027c1a6323ccd693"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "77e08f25c1814cef88b4fa0c03e484a0ea5b59da9ba0921e13778f5f8e3ce58f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e99f0a722ebe49ae148b4f11e25414dd61bb41d1"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8c93c3d7bf86a3d31299fa249decfb06816e55dcbdf01a3e174a8022fb717513"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b22d3f3a4c5dc37d277dbfec83dca875d061f5eb"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "154ce5aa2cd9aaa66230815cdd20c178b7348abf0435adbeea3c3a771bd80713"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "980ccb6d0c8d8d5f3b22a27b7768923e9180f69e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "27a2a34e32edaa627f252dda2bb3d21de4c794d841525b31e5dff47f85a92946"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3513af34a50bd0663b45abf6313618ac8f09875d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0ce4094a76d3c033f294a1504d12caa346d6a97685b41b84e9308214c66a3c8e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06845f7601eb3cc4ff863be8a45b106a44882c01"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f679e800a0ebd22e2198ef93a03ffdc12682fd0e2ac20a8b2a7677c6654bab20"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a85d2ee198960217bd4b9808e055cd8adbaf65c8"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a9aea7d47fc62bba5caeffff8538f715310c0a3ddcb1d2f3872c88a14ac22bb5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "efb60427740646baad444bf423588745ae9245b3"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "1575c5c5887b825c99090cca95856d143f9ae00bedf3ff810399897feb0ceda7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da6925106be3519a0ee0ad0428afffcec35954df"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f0c03786074fe7e8e7cc7df87313eebaf023d14e5e16c622f793d4bbcc32ad8a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7801491f0022b4fba9b8f08c231e07f4f8ab72f6"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0f0267df8a333b18ddb934d7bbd9518da9c9be49668a778e1246e657b953ea1d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ac45656c755e7ac38802b10c187c5649c8869e2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "13c1f5dce50f302f070f44d71ab3fe8e60b80fefd00d6d9b41d9a6c2fa63e562"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3e95bdbd07ef0600ec8cfecb5d9633f553c9e91"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ac489e7625546870e9bc68934270e2b7643565fbe69c57820811c7361b44e474"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "826812a35b791cc95bc4a97bf8141fadf4a9db5a"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "8af9bf9d6cb206862881f0eac401ede738789820889f8aa72783fc3b1ba834dd"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.5+0/libsingular_julia.v0.14.5.x86_64-unknown-freebsd.tar.gz"
