[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f51ad9686b596f93405612f5cdfbf5c54ed733ad"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "79201d9a3bef716ea2e9101dbbcac115175497b28adf1e546670bd72f26d8a2d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb280af7fcd36b45b1e28fbb7a60e0415fcd76e3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b4e94c631196fd8181835580153768364b268893cb99420c176abd305dc0eb11"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cb8a3171ae84975aa557d62863bcbb511267aee"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7f632b87e199702b812231a68c6b24c350db2807fd6c74b6ce8a34e3f4b78326"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "499468764d3dab43beab7e0daf94ce74110f91d9"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "022ff018df8d97ce093added3fbf91a94f57e4bde1d1dbffd19ec489bfdb1337"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e808f83b8ac8a72ee45f948da21d6afaeba7ba1f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3863f38641e8f40ba2b041090cac25692795e1b907928e890e60a42ca384409c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62eb93bd9845d9e4a97f3a8a865d933e9baf6960"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "307b92add41de7f5d093b1f3b38b6a0424126250b1f39e2ecc86e953abdb0b40"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14794cb272ec992a64b06c64a1f2969598f6d93d"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3fc4fdde8b441ebef3919a4839c2c654b911259165c41705eb1f8371e58175cb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67ac7f4ed89821bf829966c97c64084b84fc6903"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "18e48019ffb46ed76db3bdb2e98c304668b519ae1ca614c288e03d77915c5441"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34e171c369c23aef2f30771149e520eed9bdcea3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "16d9adc2b5d39370c27201c8514154d2e1d5aff6a3be81a21f017ecc9ead93c6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13c571aa981a9fce09cc8ac86a33211567eff1d6"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4444d78bebbcf1789a336d3017f85ac746e49357928f8029e11f983a6a1fc869"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "203d63d79c9d61f81d9e7f6facb70b6ef071178a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "abdaa9e51775a33fb69e5ed0b957e1c71e19d63c7abd34d30dd2816747d936c6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef03189d812611f51cc2a21d1a6431736a8bbe88"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a6d305612fe0ca1b317daa5bebb1548bac50f29300a4acb38f5cdf161048cb3d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "1830bc8ecd923dc789b5dd9b591b0bce00f20e17"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "e0d5524ffbcda913315914527ac4bd1c7c458ec98152a0022fa1166184872a05"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68552c869e64b01b5893dbc0adad86332b1534af"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "74002739a4bde2438e1c4c639efc7d0c74cf590168ea33c3626447e79a3fca7f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "263865abd0ad89e978aae3432854d566b9efe20a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "432f61d28d8f41c40fbf9b23b0159d88da414e530bea8cdc49339d5254c0f2a6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45506ac724d489d92f760bd72f229accdae3006a"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b9401317542f8961abae65664f0ee060a5b538fb7b05b88110953250de73d9cb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc827b54bc70f0d89f2072c5218f4a0728f3a484"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fbfa82abc475b1c86fee3cd71f4e175282b944d41185dbf51f27b73207583245"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "8f1efedf3b0a1180f7b1aec1ad31fed6b5738fc1"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "6505a722fe899e49703cc5f5f93a499de0dcc688931f4c19ff0df07025aba0aa"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.7+0/libsingular_julia.v0.17.7.x86_64-unknown-freebsd.tar.gz"
