[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e532e8ebea06cbb94b0d031f0afc5c991a52d306"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "660ec2e70cac5ba661c59227790df324b5237b4cc5b14f64cecf08a73c7d08ae"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f38eeffe761d30faaf9d6352a0a91479f5ef510"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "cd7d2ba99af971f749fdac3dcfb2f98dba04a00db4b0fe495325ba55a7a8e42b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59093e3c67cedb2b89d5f3e7908a7839399664e8"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5f908cd5e59fdc3c5ec85da8b32c4215304b5c62020ad1478f36adb0c3b325d0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af8c27884b33c0e0aa5dcefa75172629a49a6752"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ab1a9be1fb9c141075b792dc2a23a308e0cb9b90f1f3d3c3df4981f21fb0d0b2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "263632d1faa9668e12f5263c12d8db16678d85da"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "37e69767a0f9729ce4f851d4a1ec52147c594dc0cb7bd8d612207f793c533d91"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9efda6a2d896c2c9e588517c46d160007cfd5364"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fac30ec4b00de875c8c0353ee9132e862e64fc296f2fd7d2d60c65ee00f93d3e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1633a312cdafc5af57336b0cd9b4f3a7c1b71150"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "adbdbc7450d4554dbde44386d91e83b0cd956f70cec4cb1ac117b761bddc7711"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0df775d77e886a613f4f35414a0a9d553c32a85"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "816afc35260420f22d9fde073759cf6717b7d719621cfcbefbf1298dc3e9c485"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7e013b5eec9b0c2b414e25b913ed8cf3cf95732"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a90653897423fe26ff53924ff66343d6f66f9ad3c2aecbeb273ec616bce2ade8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3933bd6fc2006a28032c85fda9835d35e3a2ae5d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c3d9c62fbf5ae86296d65530a3483a7f482c0e95183b694c23e0faa9aef26d8d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "ef81696ddbaf0cf444bfa65e45d99ffb4361814c"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "4a86a84ab614dde3bd303cfc52a8a1db76f88d9570976fc8e9a0cb1031d47d31"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "602dfc3961a38bea24e3b3883cf59c3d086b4566"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b006b2f3b49f76e4a6ed14d7bb70006c380f3d2176d1537e44e0b1e7c7a009a9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e118e11b074e41a528890fc91e1dddc6b37f5409"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ec200a0be5740fa74ac90d3cf1af1f0f7f6736e86afc717af034de18ca79a875"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa7f36913a6cd41dc670d95fd8ae2b9202470623"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "cc3f44ca50c60718bdc7434b97c88a84a083767507274e2f07937c4e94ff0fdb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "971b12606248ef0e7c30e711f9064a910ab7e55c"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "863f7097fa6480ac1c84c9b507866da06a6305f1e0800e1a03286bc35e3ec41e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "14626d0123d904e231f31a54d35ffacce627caf8"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "24d15500993d45648708e8bdcb3ad28099c9b331d525ba4d3ff8e0407f8d691b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.3+0/libsingular_julia.v0.9.3.x86_64-unknown-freebsd.tar.gz"
