[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5ab2490fc8f66de656419e0f9a1934595ade3c1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8e3c0422afe167e28b200efe5ef99c20dca46eaf5603c308ade215a99556a88e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99eec97c4eacd9d99928e5b0168b7101014b6acc"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "efc239af286dd2d4305de3b41014c2382e1e4fd3256315178eed3b784925481b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e24826d07ee77d13a973e7c8b8629bde4302b50"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "285c2b63a54a33792fd2b298cb46592379acfef488242d668e846e58a013007e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73696e0a7f89d01be831d21b3d559ccc4008f093"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "bbf52aff83715071a00383a99273718cb4dde09b1efe4edb7005e2e278b3204b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "857fb7def6322b39e8a7c44d45ddd3e416005b39"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "57a72168fb529cf3062673dfcae320f622caaf5d7e3a03c4a10bfb9c81c6f902"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25716a0729c0f7006b5d40ff066f7504b53dda38"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1522a9e380c6095556c6d90831b02c45adab80e13742e718611cb3026e25b742"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "100f31dd35825570c854d11ea3c71763be339e9d"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "83fa3656a6121d0130b2ecb6b40ba07bad7c03b349d9014a9ebbc8a9028340b2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7517e152fb996a22b18d6b2d869b3f01ff317e7b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "146681adaffa6f26f5203f2be0147e1c96d1f960da45a5f38860dc2c31bff70b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca6f0e7bff77e8ce9e808bbb44749c244c28066b"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1a5b5a665cdba2204e505cae124e5af55f7e24f6f54c4490fda3914e9642c426"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8c31dadf41cffc59d12a0ca8c7dcf0a06452f4a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "55e622d84e44023a33215927e6d0b093fbbdf12a4f4a664d9b20b0a1ea18810e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "cc1e89b74cd49d11064562de4b89209c5d69db38"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "6311f3b230ee21d499646c33d6a14d1a97f2004a829c0979bfa61c34e15d4830"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ee1a2b0fdc9fd8d0c776b626fe996a44352816d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b270bc087404d64f9f08de19c2e0f7b1526909dee9b05b4a67e221f34d8e901b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a96f219936bc8e335e8b2722c75e6d2910d12c7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3c386482f1d5daf8f92b7bab5e4fbd4fad9a91c91a32c6ed16761e41ac6a6b01"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "426efbc0eb6c44e3d766cf00dc0acfe004c5647d"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a0ca2cc21400a3ef941179d245e210c2b3aebc638b785903cadb83f5363b6429"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "881f00cc2949f5a8ea207fcc435adcc66c281ce3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "71b378972d4040afb4d3a5d59a8f6fba98a1ced6a811df02e7700dab11a36e9b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "ad612d00b782ddf57d658a7096dfa656dbc6e536"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "04e32d0129c373f5912997b410031eb5c91ff03dae3677ffbd198d7a9a19d7cb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.3+0/libsingular_julia.v0.6.3.x86_64-unknown-freebsd.tar.gz"
