[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dab0e8037ce3631a61bdae571c92106180ca81e6"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "783b5e07dbaaf6eb35eee32babd1fa4f26885cad51834d7418a688ee25550189"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17b3349dc17f4de2e4efac336f10c0390a04cfdf"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ffe507882838ebf9cb8bef60e8c80f2b72983c7b04f7ad69ac8aeff1876954e3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "541c7ced26349341a8e5c1bb91815afbca723e78"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b61818197133e5f6b16476fbc56fdfd53c311fc2a182fc9c6b81948ac1f40a57"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1fac18bbf02d68078b315c4d43580278be6d8a2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5c2d3c30f9c1f582ef8c6e17f81c4eff5f02850632bdf8f81866b7034af51358"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40684fb4e4279f845985e92d2556797603da780f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "84ddf3e6998221860dbcb25d50f6d4d92924bde65bd6a662111b02e8a1cfe8b7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0f60360e0848019659f03581c2bc7b63a2047bf"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5c92839671a7d759dfcd517c3bddc342e3f44919bcf1c532a79f67fde7d94e26"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8617e194d6043865c1d85fed0aecbda8e6a491db"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "bddd9be7ff8f53ac193761ad6cf1f31a80f6a884088cb29c19a97cfa02649481"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "445eba9ab76e8d5828131eb734929087a5fb4b63"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4946ac2ae1cf04ce7389e0beeba1d18fc1eb5d3772d789438c43f249dbc19a3e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07991902e7b64a6d61e75c369b18df2989ada90d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "12cd8e08f206fb39780a70345fecbb9c66154c13b147ee901a42d73685ec99d0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "836385f98e38fd7938519f4cdedabb0db15bace4"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9a32e464f3127b25ec2c9cb53939fc8f678ce1d7ba1f4069ac4d4c8645c7db50"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbb41f9f33f53a6e9eced6bd9a5650d9df138023"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f17e7657d4af4208ae88abad6e3b8190d1c0acfec7bfeed0b725ed57101fe653"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2df6111bc50c671c62bb8284917e04c500dcc1f0"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ab25f0f8de9f190f510c267e5900b2883e123ac85c2597e2728faf88b8be9cbf"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "19ab21c0727164ef900ff8d091e67ea30f6caf73"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "ddca6e5670d0203c4f4d730e731ba140e987cc598eece689452c347a72db0ed4"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b311a32466eb4c4635a5d68c29b06580e657e37"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "090241eb5ab79df2371fb5e02b7f8c0c871622eac981f8b2e7502751bcc96aeb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4daa8359ce97ac229aec6695921f4301cf75a3b2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3f46faeae31f944bc49d39b08c0e8779b3e0e9463b6c9bd85f702c290ddd2489"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4c512e28f5207f66b1d5069822c21cc1598696f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a61678e8130c2b36fdd3efba98931a0422b444b0acf52d14a824f2eae480c123"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfbf64a843e15e5c3103bd38f4b6bf0a8deae0e2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "497cb18bde661dac300f1d6dfc124db925417d785fc193bf4479a7c1f5f673d2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "d8420d3cc7b33e242c165911d1613fb0ff554e75"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "fec439fe46f99f37db4b5220c294eb6119395e205659a00e9929495459290f49"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.7.4+0/libsingular_julia.v0.7.4.x86_64-unknown-freebsd.tar.gz"
