[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24b85e4e78ce44074570987973f70e14d97fbadf"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "cd8fb1980633148799e843a8660a43b3e6370141a64c24483bdc2b844250e5d3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fe57c60b3da406e8bfca04b4b389a31e947ba91"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c6b9843ab88309770cbd58c32a2428d885d99ff0d823d7390da42cef7f9a5dc3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d731609eb046fe5a4f8bacc752d64db1013444c4"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f9d957b3fa9a06877a930cca56f65dc3ce9d30df5a234113efb35dd1ec22d024"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97c78ae792b6676aa46641389e24889ad853d905"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "479f7805dc3d9bf3c0b5387f3f3f430ba4a252f365e2d0b7cd12bfd645ece9e9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86ca9611716fcad3adb6ec3207fb72cd7a46459a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "70671fba6cc6c8fd0deedb0f3c777405e61ddb0a4d25b706c1f1d1e6c17b4dad"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2caecb5087d6269dbf9a76e3e051e933bf00bd2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1b721ec8c0c285f5a8dcbb345cb49bf64acd717fe3c5c8f668a61f948364134c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74d6b31543f6c4d20ef8a471957ac0f5f6c77d7f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a9c5fb91e490b8c01219aaab9569df58b33cadddb49c6952d82d76b51229dc31"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f41bd06cbc93bc39615c932e3df61347633fb172"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "158bab74dabc5df7381be60fbd88f464f87a2fdc5c384ba73a50ba652ed9887d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b12ff10152e6ae6ec06f67bff8e39d7618fb1609"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "785bc6a9e26389d16e0ed946830d01c790fff90b7d382c2d6ebcfa069f271f33"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef535974007898bff6dbb7edd1a37c18fe1728d0"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b2133ee13aba0b0156773f50174b71e34619acd7a620c2ac32e6434d641026db"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a7df6b4ec85d097dd60004efe36770fe36b2d95"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "171ab4a98cd59ca24c28ed5ac155bc10766d2690e61f7a484eb22a89df728061"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9362da9bca890c564a110b24a2de1f7430790cd9"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b5879085cd258bbff02258f8bf24c712bd278a3af177daad5fada2da11dd1461"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "c751a2af84384212f967632c99f0029aa61249b7"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "81f74c31c9388628b7770064f9cbd838e6c31a33e56244458139073b94c10431"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea0a0d678640c6843809c192b0ec7abf90e0608c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b7359e32d98552e90859fdb9f6650a2acef75f091aea6c21381f069040d44b11"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efe52e611125a9b53172cca4cf0a2f6fd09874c8"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ce23025ed8e997f50eafd15b4a0041b5b454de6c16cdb475e0f681bef93244ed"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef639bf7f266fcf8bb7e050843eff398ac55d6ce"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fb2d75669eb60269f3b6936c79adad24fd86524241e2dd3d54d445aa5efeb8d4"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c650718ab7fd41c3c6d2c1cb16e0e1a055f55f31"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1cf87bfe6713be288f9a1fa1d1ac4519a96395547d895084b47edd7457c9e19b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "2773e0085dfcfb9409370dc4cd89e9f8e07e6671"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "290a0d02f34989808f0a71224f4b10255416d515b33327244a9c5a903e21fa32"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.5+1/libsingular_julia.v0.18.5.x86_64-unknown-freebsd.tar.gz"
