[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3169c6f271b89ba8cefac5cc57aa92c6d87f7d92"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "13a684a3dc8241589ad41ac6587c64024938d8319adecfe12e8d9a9cfa16dc2a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a392fd16fcb3b184d0f78086702856eb3680dee"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "525a450099afa9fde05d87f47e83db731da8f39b5548bcf1eb0e7391cd154723"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6cae53b93e93d905af27c22b9da35ecd6b4fad3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e7c3c63cd332bbd09bd28797e8a2586aa28bacac18df57c34d2c50fefa0a3825"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "819087a2f4706e77d98ffd73552f6a9db75683bc"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7a3f4c79c9701199bb036f85b877a5144941f0a9dac63b06626d2058f21552e2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ceca9f71fb100b117bac64831f61be3dd27ae827"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1960c1205f088bb25b4548259a7bc0aa7f052a8bce4c1203e3757a77d0cb1912"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0882ae1b2bdbaef132c598627047c1196cd40834"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5e4721d139402f24a43e7e7d05f13223a8dda75d94f12b0e10b6985c716745bc"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be31663fe1491950285253975670d3e9f3229626"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8f1ed3315dbe74e20ba90b5f653fa1af1f7a88a05bc05ffcf2461f8d484aaefe"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61533885aa6209d5d7ac25fde1cba85204feb01f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "393ca820ab52ee226aa6fe63cdff74ffb300ecae81cdc12e19e23542534a252e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "195a66dc4123ad7608978c395ea0c2f68dc3a617"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8a6e79a29950220bcf8857f4c64ec42764a2c6eff875cb4d63d3dee939d27e7b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94a4b3a6c7223466cb782ccb0142b2c6663b40bc"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "cf3906609194ac9d7804a2f405cb51b1e24019c2f7718ba079b1e9511dac73f0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6073a6c9235f38a4ef024ced649a07e3868e2db8"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "41de435e401f699d8bdf3ed094d17aecf20068fe0840b1f6c9f91c661ce4f45e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1be12dad33ee4c00c09a24ef8908ce3bd98a7ca"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b17953c8c5292abfb0ec09d4a998e62f77376418f8c59053cad1daf8fdcfd064"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "dbe49605b05e74b87c2119e992792aaa6d4e2ab3"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "a16d1dec28ba193e8fb747835ed886cd3338e500636c7c6eb5a5c05b703f8c0e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd0a4778b72349c2d9209ab64ea09738fb302d3d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0ce756f2d5870da326d5b3df115ce7186d0098ce7908a4914291d4098d8bbd31"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49638081c15e2e0f1f3e6f80a897c4ead680da48"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9b1be6e7a412163b8c8335b261e7a7432ce183a7623930b4d389a40b3c4e7fe0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa69d4a5bcb33964195f7c5c0bb658d6740c5c9a"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "497f4535b78bd98727cc9130d48971868c880af42d49cd79555ae95556a62095"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c1b4772ec746ce7dda7bba46cd197d508909165"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "54bf22c1d61a842c83cb2679b0508d5191f5cb9b7fdce037c8f6c58f54ee1011"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "7a58df914ed0eda930971bbe93a2eca686deadcb"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "2722a55751dc52be5671ce6c968be6c06077be49ec688620ece0a123154d537e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.6+0/libsingular_julia.v0.14.6.x86_64-unknown-freebsd.tar.gz"
