[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "081d7efe32367557fb25c77615f02a7bcdb76300"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "17add3ea736f6766fd1c6efafc6879356e48ef2e0fdf5fccadc4d35d7b47a8b7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0f508c03f0ce799d3d003fa9d788caa46718bfe"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "53b30bb7993385ca997fa61000baa0f1f267fb7e04bd45963e9f5c0527d517a7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "baf93d6f90ffe13c2c41a714b06aa36ee73df626"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ee6980e9cbcedf771139e0f4652f7cd286ac3dd4007d4d574439e11eba684aa5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f71527ce80aebbe18850c2c97313f7aeae4f76a"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f1c0ddecbe60aa280390aee4faeeacb45e5f06c0a46f2c11b9b29e40a36acf62"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0023a6cc793d64986e833ba02af75eed9aed1c61"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "bab12e6657a2c20b18c0f95648e7e6b4155d701ca892f8e2866d1228329143dd"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b335ee56a9b538773d25954d730541642bed284f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "42a3c8a950e2b39c4979fc77e47e37569fca8151db6ec381f1e7d86740c31f8b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af84d44f43e935f5c9a3a3a5a217e5fcad8dda64"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "da9afd499311e7c6f9d11de7b9396d55e39ac316ccd76e60645956bc0cf97870"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1f5c508831c2b645e85fb7cce84ac3e0237e975"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9cb4d91429e6784f804684e8aacd7ff99391cebda0ecadef7e03dc500365c886"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9dd8eedfc00f877ce1a6b9ef08e48e997c72b49"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c9a26a6dbd920fb94f23b166dd936dcfa0742130b9f7f17708445296f47d87b7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2e82aedfcb40c8eb404f96cd015306e365c670c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "db9156e2a83c0bbe3b0a12594c83b5f3a3ec0d2f7b2856d9bfeaa4cb79a7add7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "010953e8482ada6913d0c8b74e5b203c6ffec68f"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "fb159b6062b1c99aaf088c200e0580fe1bbf70516600de914e716029e2ba0336"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42c46dc8dd67e2a3b4fa69ab781d1a3fd8cd8b1e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1bc44a81d075ebf739679f7a57d94dd1c027c7092aa81b894cb32ea92a85b4a7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2401de26cfdc3c22b8f234d515e44aa53626937e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "697c988463f51ee4e9972261cf136c00d18a699a4c868f90ed573a52526f082e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3347ff03292c451f3b7a21f86eb6dfc6c22e57a"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "72eabe290cbe71c0e8aa2bfcfa26c43f9681ee5f94e03b619acf5deea09fd7b4"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "620584b5126a1e730ccbd9e14ea5291441101d3e"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "edbb4c9a547b15d8dfd0adf55c02435f3e3a8731256d9c5cad0f76c481b1a073"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "59c828c2408667bfef6f7b13a6bf55b8b93aa0d1"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "25947d7e28411e617154173c346b42269848795f6112a87992e74bb71e641797"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.203+0/libsingular_julia.v0.9.203.x86_64-unknown-freebsd.tar.gz"
