[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cb8c517e7cf917e7e0ab7b5126e3e89946e78e2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fc727b98f82506e2807c08a5a9371342a405a437faf304232b5e3b1acc854932"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ae521c8ee6c92ba1f42ffada1de766bbc2654a3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "08126523bc7b5cb2058c5dbd1fe1ddade7708f7e3fbd0bb0fa1ed7af4eebe29b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92aed23793ff8b7041b6c6d18beb1d794ffa0494"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0f984edb81203200a04d595aae7d64b6c6107aaddb076de3e3ffc1ac458f0b37"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1667034e10f0f41003c6914b60a5443b6090bb64"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "07d924e61ffb5927cd8437295dccb72d4252095eb41f7a31ac4458c48004bf96"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cd306801318908ebff6e0cbb524207ecc3a7b22"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "af02d3de181975aeea64ea62be45ae5a78f4fdeb93f59d149e82b14beac113a6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64d391cc2bf62307a6a0ff78c0271de4073f150a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a1f1e4f95539cc2a836809f3f5961cf172991840574bbb20c1e43b635f83edac"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "791d89cc884e349aae5ff5759e5dfb340e495690"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "927a21259b58a604e4118b29e1476bc3bc63272cd4a724d6c273b8259d140b8c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fa35191f4b792d0075dc2c921e58143e1593006"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "94c17858604813f0c207f4021b3a1ec2bc622834a33e8962c0abe1d02bf68cdf"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c79932cd880c3a57150dbbe965105364c9b955b8"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0fe2201b44122a7ebdcf84e52293a7631c0529755ea97599a57d46f273b68ae9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c0bae72b08df9e3dea200dc0773f3c70cb4fe08"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a602e94e1e7e69e16472132e9c4a91ac9f13b93b70d0b4047a56a50ba4659443"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2e83489d2139b3579f2596e722ee559e0e86e83"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7a729fabbb984d4cf9a8b9a4d1d2850f9447994b6d975f9d8ecd77873218313a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b7501d8abcfbcba7a771050f2629be2c7cfab9c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7c27ac8d8b9d6dc71c464587ad2bf05b604fe61dd7422530aa4fe07b3f1cf92f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "55129bdffcda1e8b1c379b604ad3bad4447e1d01"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "685af9658659d9c78735a03a5b39064d8272179a3aa899928cef33fbafbcef0a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36c9339ed08a76b46ab4f4908b68c00ba3e9ffa0"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "adbbb29bd5a5268153e816083ade52a382dc46fec653d4defb495f592cbeef82"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f268142dfd8ae6a20dae5061bea824ab18eca97"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2f97b0ac24aa87255150b9eaf9f3bdb209fa4aa4afda72b21cf4f7e81cd4fdb2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e90b3ab9bc072c2fcd339eabbcfa6a39890ebeea"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "28ec67ce6593e9974a8e18016d832212feb8fbcc229f2d80d840a60ad9bf159d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2684c39f9df65df18b390860d67da517cd16aea4"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "dd6bf6f80e5480ed6cf9620d8285057d68906a19c409d51a93efd3af06532513"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "3e3335a38bcbf41947d3216de5047634c52d21a5"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "3782aaf3b167a1760f0bfc9a7dcfa74d6d29c8f035f86b1ceff7182791d70340"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.4+0/libsingular_julia.v0.13.4.x86_64-unknown-freebsd.tar.gz"
