[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d83566426a07f800f0a3d99c360ec019a5b9989b"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "90682c38ee89223214a8711330f8723981f72d6f9e6414c2634eb33f5017555c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76ae83e9c0d3c0984f27bd198471f58c2781ac50"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "525426f7b315379a5dfa918042223444d4427b98d3b79f2cdba014cc27641eb7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea320741253a1337a357c64555070384b88ba1d5"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7baf51ec2906113b5ab021694fd476eaec5ee60a1107c19e5f2388ae81ce5e24"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ae0d3ec79df9a6204091a537ad8c2b92e72ea5f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "55af8ba375078d27c603b1a92a53236d8baf81752bfb68f1312f3f23b02db6f3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e438fbc9144726d94990c5fd1aec1ec3a253841"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8043216918fad7c2f9cc94b8ffc06890d9e82345eea9f3737464a97d7d63befe"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1338ee48b77469ef8cca0fd448806ed866b9bf09"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4baeb2c14df1695fd012b98547b74dbfa43bdd6e140920c95bbac19346666fa0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fdc7b061269adeaf3f6a902faa5890b2365bb3ce"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6fb97bdf7c0d3b25f1dd16c5040b2944e593a4b99cb4035f7e13eb70d467dbe9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bea2953fda5a121ae0a098390bf45d18d94990f8"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d73c29cd2819773b255d51416318b6dc7ac6a17acdd24802ce45dc99ef2d699f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89b82ed2ad88747dc7ffd7689f1b9727246e0ec4"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a60b028f6fc9e0ed3eeff308566afb8e12b866ec01fc20d31d2a2f8883f0cb2f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30618e78146dfb365a0a30c3291497acd17975d1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3dd3551e0ed8907753d0a6bd86a11841c068a91b25635dc34e0c13863b3da15d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cca5d455329e7759f8bcb63781f23b79d2fe15a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "24845742db57c09cf70a8619b05a19d611b4da2e1dbfcbd8e466b1b6c1d99636"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e54fc68a57d2d8aa544d797f3e889f4cab85825"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "22d0914b1b7903a7457e652ae1d367f98c6f78ff8c5470642eb668a7352cd4d8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "02d4792a1f036e49923811d80e828b7640e653e8"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "666f1ec58e6c5b3af99020cf9fbb1beff8943923c0408fb24d0f128363057ae7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7a5be34e4328ea3c3bb1005a34180c3edc6f0f0"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "137e09c51f97aaf565661de80a966d42667a047a18db670d6b4e0b91641266e5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e39b64a00d41882b63ddf1eff8691464141b61c8"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0f801bb3a438a035cfe1677fa0b2bfd52396b49dbb24de60ff759d3f7ad6210e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ef41d7ac2df1473a187c027f5ca6adfb1998b77"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ae4b1bf3f08be13019356eaaf8289f279bb0d12307a495b551a269d8805f8712"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5523b39b20e1f946bda1855a65002c5ca29cf34b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4084addacc9a082d358e4ada67714988d4307bcaee92aa4baa9bcaf072363b3a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "f0dc625896f5be69de75d5257464b9cf8c7074f0"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "73cda0d6d4e3f13f2441c62a61e88f2f8c64be069424016a42b50171ca611054"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.13.5+0/libsingular_julia.v0.13.5.x86_64-unknown-freebsd.tar.gz"
