[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4800c9ed95804f6d6a37c14590e8217c150d91da"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8a5826c6db8ccd9c9434e2b4a88d4cc48941484c401b0a77336b51166c8b4648"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18945eee3dfe970cc8ff1dbf7ad71ec547ad06ca"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "65e065baf1c916bd3f9be42550dc7745aa9892faf45f556bb8319da18bdd08a0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ecee304a6e7c4211f03c57f65cf9e3a1a1391b53"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fa59fcdf6bfba881878f3f99d91cc2a5529adde8a9d3efac6b9f0fb31a8b2503"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e03818ba0c17cb00428eb2e6f989952cd586bf7a"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "72353069ac266cd0220c3374d638ae86f8045d4eae6ad77fe2e13b14ace47d06"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fea148d886b0a28e9394f3c7def8a6ac5b619a9b"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "34ea97d04ef75d1784e0aeef19135738a9210588fe7c402550be34f38cb29069"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9368090fba072fc3a68724c15e00900081bc4bd"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "82843ecce758e0b9e690a2eda2b4070f3b08b5b53f2eecc25182636fdcb02644"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6020259c8480e527e4cb0dd12eb0298bc66c8cd9"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "dfa0f5d68f17a263bd92767f119d048063e01397b5d41d62393f3af437f241d2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10fa38caf5185ef686c97515d0361c76059a7be7"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "30f7f9a459b70043d22824fedd68e48f90989b5e0069d9f8635deb5d48dd6992"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a604d4f1dee89f608a89a7378bf90ee01d9a1555"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "309331fee8c6e14a1471a5a6e817a8acdde6a2638618abab1927935e907fee96"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "386ab96118a84115d8e5bbe637514660e24881d3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "949102b03a5aea8766806233a292787d7e6c259bc2f5e1aabb1d81d227bc8fc7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "903c89f85d866c9d57b7d024c36284fb4bc71870"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "7097ad53da45bf697ed2fe2b77dc46319cf9429b4e4e672d947580a75cfc473b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd6043621498744fdc3f23ff3ea99c765158f1e3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4b497e4f7a3c787017373601acd9db4a8e906e84ae27fbf5b9a42f52f515e590"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb3afd84a5b22985d9c6342211f900d012e27028"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5b781ab28389d3e7e1a5cf81b36a8abaaa1cfaade2ac7603473e2d27f034d781"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62d5a727f9953bb21c58d7d3019d5fc67a9bba59"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "137705d23e0852748456391438065d26a14b80221bd8ec09d89e712f71a91ef2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f949467dbd43afa798c683402d8dd578f1ceff04"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c04a7a5e713b5bcc605debcf0bcb6b3425c0cc9af1a5851f6cf96bdf9f69e5ec"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "0bc8c73ba2cffcad1f58952f07e463001062046c"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "f8e663f555c55c990df6c0f59d8504b6e4a1f45cec5d85be4c5d8bec8f8f740e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.3+0/libsingular_julia.v0.17.3.x86_64-unknown-freebsd.tar.gz"
