[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81439a708081837770b842eee85dacc22bac57c9"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e9b3b4f558225af067e5a486683841cd67938bbc04271624ce24a4eef15121e5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6db45db15244f9fdd07fcefa9e69fe524ef057e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c0e3e95713669b6d1fbc2d98071c0c7babc494c04a263dc656ddac629d2d4a67"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac6ba815cad9e52d31b84e27a72d00289c60b497"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6e8a096f65a715f046fef1d0aa64c9a6876a93ea70a70aa9de41802222421369"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25fa0db690d9de912edaa45b695190a689cf535c"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0ccfcffa94626665b09186cb98b95ccb2e5a1e3d11251d9e0d1bd5ca7cdd710c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc5cde6663d1db997607ae62d216048d5f430b97"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f8e8996f20be9e0e43d6da8d792ea6a1a7b91f5fb38842eaf60b55b4b9c2a6d1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e8982d5c9fc94015f16e4dd40092a1ab61f3705"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8dafa8b08b80c6701ec04dd6d16bbf04c15dd63dbb1e041028e5d3d39e198df3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "557121095673918e17405f078941b001d40cef24"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9d4c69a1639320d528ecedf0b4b83140b1f7e8db0ded26af748e1b25756cf48d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92b06127823aaa44dc5bb9169b8395549465ba5d"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "11b55ef8d40b9042c2a04e0be5e67649293813a60724ba1e5b759f79a9c17724"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af17027de5058440c94ab3693f4d537336b3f099"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "de281a9f8965849f1ec743b49f9df625088c18680c9ebc73422c7db064065845"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5220b3b8d03d9483bdb3e6fc9703e201f9b7a2e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9ced4f6a5f56aea346f4ecbe9224b58512cf544c528bb28cfcf4c5f05c6eab44"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ab37bf4e9103997f90a5685a06ea28b72dad585"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "22c83f5c40d74f1ee6ec19942480bed0cc0e60d1f2cde51ae5888d90616d6db3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b26eb2a2f5554f97a138a1cc502973c0b7c55cda"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "db98ef46b7b8b9efbe4aa3ffe37423c1f5ed82b2925907f30f6b32eaf374093b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "10fcda2ff05284439703ec63942f96b1a09dafaf"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "bdea794e0886a5bed7f8e41d288a4e416560cd1fd845de3179b951e8b1815de1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "16dc693df79208c71b2fd957b6f14ac22d02466d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "52e9429f12a9276033c5bd07180289923d6f6b4b86bb88cd6e0b7ac3737fd533"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e164feb1217d11cd9e98c5b3bafb2794651787b"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "24d91a8bcbacc0efb13fdbc71899913a3beeb74681098b8e4123c4d56579bfc6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb9f303b4874b57afc4ec3c0df79976dd11f6176"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "399078d6fe30747b2ca515e31522cf1ef1818dbedfdbd767fa483bf6e6fc7cf5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a9ae79ed4ae9f34b42496b8965ca8c969d6693f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "95ce75dd16369c4a9be5e8186bd7554aeeacfd89b24e064e45113143a2d208aa"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "012d63eeb51cd0751884574c6caaac5ef9a2b44f"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "4265a7a70831671560a473d603d09488fa678fdb888dd4951ab0c72fee78183f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.4+0/libsingular_julia.v0.17.4.x86_64-unknown-freebsd.tar.gz"
