[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef096e42e8df2eb2a1f52951d0c40003fa10b796"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4de7e65f08bef9815e77f1e7e6df3f3c7a50a8c8b08828ce38637d3ff3a7aaf3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4268bbf62b944940aede661508896b3669bbcf0"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "57c7d1f6a9604ac2c74a0b12e055b6d9ebffc59d7c32a444782e1e384ba67c58"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2636c2fd648b584ca3ed944b0dd931c37044e018"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4f52d36808d3fab05fb9ac9a914a06453fa18ac02bd2546cfe9f1a68955b365f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ae4b9bb425299dbd81c25ef9839576a6bc489c8"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a4c687e37bf1a6a7b370ea71ea678948f9ebf8c6860f622456d2a1a87987538e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43f0afa83c160fda411d68ec75b48628c48ce2bd"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "421e4ee09b16b48f7c62418b15cc8a79935fc53802826c6e00908a5248edca5a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1672a2fab6b7eb48e552500c165ebdf2a218f5c4"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f9663c60b30f7ed760ab861f5bbe98bf74130f86ac16554471e4689193a3ee17"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "854792e4699e21abb158a4f1e10c170bcfb6773a"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1af652f9e2e4ebd02dbc2ef67c6b46a0bc6e7e8276e73d768fa4943a14c55bf8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e59165f2e93cdd96b5d12317a9058b1c4025291"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "83fd9c94b187b1d0a2dcd8185ad22dfef53ef2ed493d36665bd20e72a886254f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de43895d42a8191463f11914f5dd26fc8f7a4b93"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "329e3b377a7660a02bacf30014d6e28e2b2bf3960b763decb67867febaae4a82"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8612f6e1c07d46fbea0bf5b551fb44870bbadf57"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "975c319325c1f72f97414782681bdfc6945137345a1087ff28bb51bb4309a2d1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "6bc796dfae1e57f37ac6b87e3f93ac46be54bf6f"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "f8d082db82362b8767feb5c7999e87420bcb406bf710e92bf06519e71f0e56ab"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71cad5eb269adf967b8d9178f262b6b5e2ad8754"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9d60f7b6edd745afff29d312cb3446ff1d3276013fa0d109dde366b47206d466"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21661c98d9a6ececad9dcd07a8f1c3122058cf54"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4a3712079dd6d3c4033be6d6c26e1bc184edc4f68697b20b8742beeecaf5cfd5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "148a3dc41143c1e972eff09e2b29d1800f68ac05"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2add7fb37141ebfb0ece92a5f7ab51275cff154a0059eaf18e709ef765fad4c7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad4deac9e69ed1657c191f43d3790f1af759d4c0"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "daa378ce8353a22b969d7440d0650ff1103d40447d9680c8fbc20626472f3ebc"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "8c8b32c28ac0621725f8a6273f4f4451b04a6f69"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "8dda736192c96dd3256a77e06469b230703452d9cb4ca58115fa25b396dda87c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.3+0/libsingular_julia.v0.14.3.x86_64-unknown-freebsd.tar.gz"
