[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a1ca8d7a3843eb509b0ee4397ed3bef7026d2c7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "35ec6a918254044130aa2abc1d2a7d3214d9d9dd1e42b4e1f308ebf122facd9f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8aa534ac02292d09ba5cee72a13ed5e1fb2df2e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "762e2e870f5cc38f6b7503a019d4d05f69bb92098e48864f95c5976f5c9b7e42"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "442c597cf78bc3ea3c0b5a9de9cf4ddfe0fb7280"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0cc114f570efdaf78ce69dad2e1ddba533fb7c2101270e4dae2a19e87b7bfd1a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "714af103df1d28ba91eb66c4c1f25c7beafc6eee"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "90c802cee666bb89d4b53ce9758f5c91f3f80290c1f078e3b03fce7d778f4103"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd04bda4019af49fbc6e9905ecafe2616b86020f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b8c7006f786a2bf8c2dcc628932e32ba18a5f4c1662c1e8fdc61f0919cd5f27f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44cb05a87e03ddb382c768e3cec5482812eaea17"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1fb0e9c233ae499e0ba3d7705d8b1254af241adf0f6b00fd656a29cafd9b9dfa"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44181c2a37b7ca8c340b4249ef1f39ec89a36a0b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "08e322ca53d738ddd4b4a4fdc5ad3d0cf014143c2e6735b8f94adc70c110874b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3432c145298b76efcebce1dffbec9bb60730e2ff"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9271f002ca2ebc3b6352d42271e4f125e7e93bf3e1bc811bd42d64be7de92a22"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58647f47b6a7c566b654db74e1efe2b3da798c8a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "641820c8120b1d07a3a96d34601562989767de2fdf837d84e490a7231a7ca12b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f085b685c793a6defc4d379f79844f31c7c035da"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fef3ee52f333d5a5bcb7609690586030ebfb08aab650b9a47cbb42413271d07c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ffb26f0ad57c5b0f8af06b47f410a912e6df4b29"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "459498a14570e9243db84a89153015faab6dfe4f5004db1f629b0dc04e8a72e6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55d55a87552c100ee1547efb4c4dd4cb37bc8268"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b1faa7ea052afd5d7005db8bebcc92d0ac1a80287f01964454832cab9d1fbf1f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "7866d3fd137f94a17c23d6f995b53af7ebbcf4f2"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "8a5181118e913b3ce65a3e941644be8a3e91f199ad1d43d13b745fa996f47b6b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "685901389a3ccb649a8774696ea29f17cfbfdf50"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4c15e8ee96a651892fe69a868b2ea26e496516e9b39648368505b163b19cf479"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29fc1cd190025835c28c63f49d42f75ebb716bd1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "09b565f01b5cae4b8b322a6a570c835529e02a97ca99b4173d60e43fb3325450"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0867d22e5efe91db306ac074e8dda3523947c81"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1ae94d2d49891a03d211ac2c2673eb197e59aac0f8e01814052d8aa5bca81630"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93bcd5b92407095b7661d9341e3391cf5d67e9af"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "facb5b2bc8d1c9c5e702f64de7b71cf1416c3f43fc2a9d4122c86f73dcab33fb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "e56be1cc3aa3ef71b94427aeef5883ff1663eca1"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "b23c26c16b52255967db54c2caccd4ad27b1f4912e92ebdf3b82e840cf3aa662"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.6+0/libsingular_julia.v0.12.6.x86_64-unknown-freebsd.tar.gz"
