[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4ebfb03d0cb93dbdcc42a0663da7878295fb796"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4f583dee1d352adb2550ebef056999b83855faff33052dc6e5adad2a60f288fe"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae8660cc92e25d3a7c4b00fcdfaf78750be0bd35"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e0c851260d29c9c986f9a69eb06cb77768853cd588522fba47713e72ea7694b2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05a5c8feaf099e0f89bd42c4b72e9c0312f4bdcc"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6204b8837c8bf97cf07c8b0c0fb9cb389b8d44d27ba191bb2a67ef192a0da09e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f306488502948536029920a0bf4488d16be402e"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6bceaab0ceeb860eb51d50f4d8e9bbeff4612b287a59e4c0f1cbf05ab54828c3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c7583edd0889e80ee2d695f4c5127e22ab46609"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6b1aada7b2a18d39c2ba2b733786f62518a652bea7be25231c188eb6ccfebfb9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a9f8fb90e6211e04b39ff8d1285e3e67d2256ef"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fb4404fe8f07293e3af689fde6e136eed24f5e3ccd22d855ec7c9dba0b18d7ef"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be7a72e70127dcced5517709f45c1cf56bf4f1e8"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3d3a6285a9a63b83a1193e39d3acbdf7af31dddee8e94f2eb0779bd8dfce97db"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0e4cc143a128c13051370a2a66891503ad5bf52"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2d24dba5118affee143c2df0a22e6deeeaa6dab746b1dc582c8e58653b256e41"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cc3ff7a64b65133a5183d291515bf293f7ed5ce"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c7032c99829a2ba12daee3bda574b568b70c69b5b8ef61e21fec94e3155b8500"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb5aadfc5f13a156b1a2763a4ce8e1096408b796"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "27837f548f29e2994948a8f957202392e4d1dd08bbb6c8c770bb9a1df0158be8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "dec09bf7348cba56754a1322be97b6dfe7c271bb"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "f088d2b933fabb5a1fa63f6e3cac5a345a0c2e886d99a42f8180be902cbbe30b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fb3e4e7be8cec692f68dbec00656dec46dfb9af"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9d9341b62a5f7ff7791475645666d6c9a05ad943ee6a7cdabf70b4281f991466"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ff7647d7cdab221abe8de017b3c429a8d8ac1bf"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "39aa4d6b49a0b0eb4bb58dd929b8ac8fccbe296b53754e339580b5e9fbaed901"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b2bb8759dbc0fd89ccbe87e8455be7c62e2d34c"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "24ce0b641d55c2c72aaf2bcf27b672e8fcc94f0a7069dbeb09ef749813ca275c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b09284e8b7353feee7718d94ec143c1bd5808f4e"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d09d6bcc790f243253eeb6d92e583d9f3ca95930687ba6cac2fc8e04380222a6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "8aab0f53db995435b5eee3d6ad05d68035dbf291"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "5306cfa8cbfe0276a10355691dd37fd6ba4289d79c79f22d43533440b7f9f4cd"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.3+0/libsingular_julia.v0.12.3.x86_64-unknown-freebsd.tar.gz"
