[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11a5c82cf8959a834d7007556e3fb721746d6e6b"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4fed96ca510d5a96adfa2aa5ef054cb97915e018359a91ce53d6b553447d1319"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02ff65c37911b096ddbb6037c36a7046f3b83a97"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "18b166e7f0eebb2ee5ed419bd20f31f0509ad373184544d851a38a76866ceaf6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14a2c4c0a087a00b1c0181d162812f7ada0e0b40"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "548da815c37a2e761d40ae0ffae884241e241892a81e706ab4ee2d9df2948fe9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c03fab0bd149b2af47370fd070dfdd4a40e336f5"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6cd2022390f74961c69f12854a30a2223dd78f7d2da61313364f59b2760b1701"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d0dd4b04c0a458546021a223364abf967d580d7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4b6e9487e9ad2eb36973631c9cdd61c698dc6e824356a736c1dd94f5284c9433"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78506631887c662a4ddd24147def3dd4f133bbaa"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1b5e8bb9979a9447c2cf1fcaf738733b7a8a664be498f590e39329bb89404b9d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82ecce3f1d76165150f156bef3e3f764a36bf886"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d89be6b21c4831e0dae1ab2a7c80f242afea66261a146ca120b417e7eda02aeb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "399eec549d91de7be5e636f046da270c2200eb4d"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7cb75110282513e94f9a3d425b1cb8a0753bf9eec1b8f28a55b9f703746e6731"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3a2ee147fdd49d8a85c3a753a1153b70387c161"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0b5f37e116f5925c00c465641baf4887b0ec0af8b59f2f7fa3df56eef63eb4fc"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "017a976726e92ba4708d7e04e78a713bcf37f75e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "12ae00fc5c0b82dd74ddaa6088d338a1190d63328417fb181cd41229761a0ab9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a09a56e01de9f5eaea55b33dad6b700a54ca4792"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4f83b97924f0b3ec2c8c86da719b6c005107efad0a0f471313604e5ed039e006"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdb36d37fbe699cd126ebb0fe5686600ffa522de"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5c614ce9c9cc6cc4546451a6c95f7de73b86c453c25f8f1855d9857a4b463b11"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "cee5a32ffa2e576e5b4ad5a7ee8e9cd6c52b5075"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "a4f73dce49d7765e557220f55cbf6d75d36565cd14358405c5888627ef58e727"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a5b1c618cd7d91f6619b80365ff8ef2f08e2c16"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "045b09f2b3e19ae91bc5083c9e2646700c7c0e4c4931e053fa11e1199166fbb4"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9122cb8b1d99c5aa4483c6bcf6c121bcbf0990bd"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "acc5a98bfa5604f9e23176862bb6d566d24361596356d2b3b8f38a6f9e6d1773"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d142d8791adef4435d24d78e12ac9df2eef9d8b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1f79f613a9921d4e4c516f66556a9c66576f680070cf82a35a3b570d0d85fdb3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4e41ee1a74a8d03cad81cf8566ddb866310a639"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a689ccffbf15cc6ca939d7cc8c186aa87e3c6e8e3e0d3b2162c45f7f3ade475e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "ac562cfa3b5e7b60016a20cefdd9a26e4b0c2aaf"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "93ec06c9ef55f7a61a6004d346e784d23156a0559ef84a47c5665ab417684eec"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.5+0/libsingular_julia.v0.15.5.x86_64-unknown-freebsd.tar.gz"
