[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d443356231937c878a35b06294a1f6ee9feb6b6f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e0cec15e54b66a1fae0b09517510731e58aff3c7f24b46c39726c9bc06965338"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3863b4e1ff561e21d2b65644fa572888bceb92bd"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "904cd4ad56d961965313029532e4f7e3f2d605ad3e3c967c564fb02f3e02a4c8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ba3d48f866c9ba73c741514ebabaecf4fe7c155"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d2b457ed24f53f3efca7d9c249d19a9ea0c473a81575f4dbd2a975a1e1b642d9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "731a01d657efa72d3ffa1612dd67b17a1c0b565e"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d28137c74d32f0524bc9f619750ea36534f474923342bdca060d09daca9dd2b9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39780b1246ee28966d497bbcdc0c56a8d4e082e0"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "69f82061ab43d18b7a28cd919b049ffa61bfdef14a589eff8607444d1e6a388b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6622b54c6f91147eadefaf069223d944077ae25f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9228e54005b776a8d106d1c3382fa6c9585e7337adea03de43ad320ada0d9a3e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd175377d544de46693783d6304b0c73a0dd8d38"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8364e307ce9ca436280315aec9d63c35d43056bfecac2830cdccec8167e78d58"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c7822a32fe03c07b0924705328287c684457c94"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3325d1418e907c5008fa30d41d213bd85281a8500ff6e53b351ea242745b740f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1a147d6a2962b45b4dfff236bac8d6a68b0ff81"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "669f0347d645da7b636906f74df4a95da0dbc6583f540a6e71e76c1d8e93352a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c0cc86afa4e1b3fad1abe788bf3f971508b0041"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "383aa0cf49d27c382968600d246430df4d4f44b1dc58ef7802064bd6f16d8f2f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "9a9590b72da8169b2ac9013bef4771385fe03416"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "600469d5c6d26a15010321bb30b3ebdb7a6fa3150ee77706524c72b56ec9c69e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f985a53befc9fce1855b458e8627839f4e57cb1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ddcd4c1764f5ff1223d8dbebf62857694c580970e9c150e7047af28a2f8db04b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64be05914160bc38613c5b8b5bdbc50fa242b8c3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ca46125d25c956ba0857837234d7d3d32274a627dbe042a471fc96ea6c475fe3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0fb706528d92162f33b66cb2ede91dda7cd1424"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6214b7b7b47eace3c1c8f864acdaa1ac95ce831e480485a674c785ff0f8ff0a1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e8e12976e18f0cee5fbe20cd3dff0eb131a0980"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "53184a1845a3cc42899bd2001afb1e6a7a0f9bf4f5746a4982be4fa835b8f7cf"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "d6cf7b955b117281b23043dbff82081c1f7afb16"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "5d616f4f2e9c89f55cc1ab89c1bb4a451295cfedf8045672ed38442a8ea5e30b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.103+0/libsingular_julia.v0.9.103.x86_64-unknown-freebsd.tar.gz"
