[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab91012581d3010a33ba960c67088bbcbc7de913"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5075d239f197e82367aaa872f3f081be0d264e0e4b62ce4471c74b37301deb05"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57fca4c58dcd4a449b47decde392107bdb6d0ae9"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "eb4fc6bc66a19b9c3fcc7d8863afb8fce2596c130f66a16deb2c7dfa12145903"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2cc03219bf00318489bb5868d124dec8fbfa8f2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "36722d82247ca759a1595bd8033ceb6585146e9475f5d241bec6a7d8a270f66e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7eb469cb245009b42e41aa3e5ccf914d119ed4cb"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ebf842e044d87c97ea5f1c85343492e9cae4693aa47ab0eec3f7e5c89ee2eab3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "647512f5d4e38eacfbe5542b9b010bdc9888ffb7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c6c3a653dd4fd45c3daa3644f706711f99fb4447c7965bf53c18ad33ce4418d5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be664a64c22dd185d68b6db31e364ad0c28a2657"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "777d85b1867e125316328894f5285594d2df42ff38aa71dfdddeb56cca38ffe7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2e8d6ef669504f5db00035fda318304223b16f7"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d3bbe33cf228c34e04d51bd43b5f9f051a8f610d38ce98e16e3ec90318362135"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "378ba1e5b68a8688f367d3a254fa300b8e45cc9c"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "27cb39c43d502cc5ab5030d80c31721157a42e2a5071dd888f9372bc394cf4d9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c3d5fdded15bbfc01b510a6f61d6712edb43965"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8168735c5033d29175c29c0917fdb3529e7ddce4783dbfd0f33e4a99c6dc37f3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e48f1673768368ddd4a1dad55d7bb3ea9ca49bee"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "811c9651183a24da170fff3afca7f2d97f30014229fb1aff07c7fb1a4a865b74"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "78ec5dd05824e05f5a1f7db25c8e2e7f25974c33"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "0232f394cce87940cf388c692578b7777641b70d566495fcbb2633382365e89a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f529db72102023411363489b5b3d8b0a90f8538"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "393738893cb06356a8178e30b2b2d73033e4455f97926a8960476b06e1d1c327"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d160dde7fe6675e3ac8035ee49e256cfef9cb1cd"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6094b1e7a8f45cc6b7f09f2877b1759fcba9bc738459dfa849b49b756df5e749"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15cf646ac969dddf9c27f119a813d4977e82fa1c"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "161af43b8c6b77cbfa4eaa1107c522af41c828b13643a93c751ef7bd0cb6d4e3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a2f0c7de980ec024ac6ad42aed739af7875338b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "226003f7b68cb937d50755fcdaf59ccef25b678ecff877fe1fb2ff493e88f41a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "106e8d0834a03f2986cec73abadc9d95179c9657"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "58e69154db71628959998d25c376d3c23d868b2f6c3db661f99a50bb8fd6b6d8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.5.3+0/libsingular_julia.v0.5.3.x86_64-unknown-freebsd.tar.gz"
