[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38394f3c0ba11d304f3fa2449307c6c28b640cf1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5a35926d37506814eab7c4e0ead6189afd77475846ecb0afb5785ac0aa1dbb37"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c8153e3ce64b416cc1e2441711ae4dbc6af3346"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "971f97e17935d882cfb135fdb8a947c18bce44a91ab1cc5ba4318cbcec2418ea"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "303876f3358c1057be1bff2322bcad31efa044e7"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3936199982d7c4a07cd824713ca8f9ad29139599930033f3023de60ed36a05f2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d7609044092ed189f180e9d7502fa75a103b1db"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1da0c04aff50bb13dc17ee75bafb73279d08221471d3f191b77f0dc4e396e6b0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "219c8a80d1c6f67469a45d1cf2a38d2a1697d936"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ae8eddc26ded1042ba9f26fbc18b475625d455b9c630d3e5e4286117cc3b7189"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eec68c29cd08d6231a67a613113c0dd9ac53717d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9c72d6c91a2860faa365bf06dcf6ae790ec3b95fae0c00275afb0860459e26b6"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "033432c421e4013cc3ca967a589eff9022950955"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3f3a2403159193cf52d708a46d9de9f0689f3bb7dac12609fa1737f3f9472ab2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6071791f0d7147aab6d62ee9d643c71b10853c87"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fb145853ae9e3e5e9c28b58d8d1b7b55641ca9ab4dd9ce4121677ef217ef27f7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5eac0b5207c6574ab4a21bedacac7d12d486c7fd"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "db8d0328a1ba0afdc5f5228558d29dc0fd682cd5b351893de8c1dcd38c74eb05"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1da1bcbc0ab597b2b77f91328cda07875a04d3b1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b7308a0889bb9330dc8fd68d21f75dbd4747eac3c8f84b381c81a64db8ca4742"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ca5e4cc415a0b0c67bcc0fa3c516f401b3a2c26"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a0bdfdd0cb24c7ef9530d90da0feafbbb7560e491b35c5697e28eee8e1986572"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0cc4870fd5838805ead579eac0ade5b0acb3d05"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "dd5fa9638b4025c210a5078dc04d95bda95b90feacf999dfeac3ad8236a6edd9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "eb4ecdd84b0ed4928f6a6ae68d8173d095f371a9"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "11286128ef319a27c9c05d11f38337491897d2d63fd9709cf1a8daae28c62824"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e46bbf4d14d946f1fb0ec64b234ed0be277e0c18"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2556f61b0279d22ed62f13c868f9f60061a2dd0e9eac194cdae344d5ee136a53"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80cbbc9578276ef8dd8d3e2a58fea6e4c99de23b"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e37970ccfa2d8f4073a0b17332f5cce9ec5a7d7fba419f8b0e0a3f7ec7f1e4e7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81ffd418267018bdbc1e7bc90eb6da903dab24b5"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "acc22e3490e377fe643abbbe08bcc2e0659d5868d4b53eb60d822b074933e3a2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27d8969fcdd54d871e60b2c66ff99a98b8b3921a"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "500c4ff7f989f0010b2e7284fd7cafa78ae9b7020796efd0ef822974efa043c0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "504606afc69087685ac6b77bb4d69bca1b8795ec"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "1babbeba98d0b6c6eeb8f43cfb61731e033ce5c98a456d65b164b5ad4a6334a2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.15.4+0/libsingular_julia.v0.15.4.x86_64-unknown-freebsd.tar.gz"
