[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0895593fcfea6f2acf4673fae5400d2d1420ac9"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "54553f0d7d5b4d37173e7dac193bdcd8b18fd04cd63b4b1a7f54c41259a3492b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f0cbc4766c0656395c97ad4dff52f252bf1f1c5"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e0dbb10b1d891dffa62968527a0b012f9d7638fb0c2d2936dd1f7c4405a712e0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aaad4fa0367d0eee43361386677779d0dd4875b1"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9340d2ffe6d55e5b1d022bc0902e36c9605de772947063ef19d89f5e22c565b1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7afd76c74ab57fe9e3a0ca2c8318d61bd5c9480f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "51813641b523087d2bb7563f63971c54ed60ef1b371b4bdecee0cdb3c4b5ae4e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0451176d480d2f3b1f2c34fde4af32bc36ff5e0"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "74aa6deebc0a6cca4f9f736436a1494c5890a36ff8573959d0f2638df63ab443"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "838d3fcca029c7d35f35c7c1bb8a7f5da83cfcd7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5c362706536fcb07a7cc95314a77362732a1c2dbffe3ee6bd90182f8895fb648"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d7bfeced110d36e38a8ef4b6b2ef3ae5a8ce859"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "690418f7cece262382db20620779bfbfb5dca390274d6da3250a2832c49b9564"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a12d9d52a05c5e599807672caa8cdb9a13d8d60"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "69ea106fb3e32f2c7ece1e57ed6f71813b06b65bbb22d08f1dc02bc5471b4aeb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd1e4d2e1656700d59a300d2381d27c680ff481f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "92973aa02ae9df6d95c660b873f7b71915c00b76e355e3ebea743fa6f365afae"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "097ce083a2fc20b4c0acc9c19fad151a553ead49"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5590e75e4a4e9b3daa89aa91ca39f2d9890c4b6f968b4afa0024833994752b66"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "207003e2c1fcb7f6726f7a0e0b134cbb002bd8d9"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0ea7c02e184b5fdb443866e55a420c2b3f73892f2ace2611fc0f3d10f16b0e59"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77c5ee5f32a94bc49f843cde7d6d0318748aee5f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c023bbe4e82591fbe2969f2e065f90a239c781788c5374b635795e65744ba4d8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "12ad17f4f1de2ae89128fdb4570d3d25ee0e7249"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "a883fe42d08c52712250e5be0ffffc4f370881b41f4cea1781e540d11ab910ce"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "455b379d65df42e0aa07ba6b500f7282d23e182e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c3801de9ef48f975a24ab26f59e87e5f4dd7a991d2a9e7c50b2fe51fb8b6ac5c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cebde41d53de0b13580977fa83b996edafd8a84a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "841a494a07850b00d217cbf02894bba91e2683c5391c2511b18cd1445ce67092"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2eccd9a5176612d63d16e7a947b096ed39274933"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "618b976cdd3ee87c4e75f7f9662c043f8b0ef144dec3431a011ff5fdedd83192"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2213a5b4ba58c50d9e9db3500249cd6c8b620d7"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d8a1d461790e306ef740ba3962f721c1eec6095d6408648cc3b2e0e9f790bbec"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "7f6c220a5f0e8e3c657977f21bc68ea926376b9f"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "5cdc48d45e6b8efc8c9e8ebb669ea7da378d72b23f9928f66f2f2bf9e2fa74b3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.4.4+0/libsingular_julia.v0.4.4.x86_64-unknown-freebsd.tar.gz"
