[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b519c7a9beff85c341af7dd2c5afd43b702aba1f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9b80801b023d95b301786ed1835b00a4071f454c6a5b96b9567562c18b8501e1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dc1ae9e3966cdf4e5514d62a321572fafc7774d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "683a12e26d38ca513047303bf1af1a4d19df57fb01d21f594b1bbb7d14bfa601"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "138c8fa0ac04677a6533aa28183b88d1ee7cde5e"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6884e8146fac0c8007213f3bc510f5e5e1020825647673a715aeae32b4700b20"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4707a9b4739df6a024792311ab80f3dfd6f0b90b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f566167273370ae07e759147a760d89138f04f5e80bb0fafcfa2c769189fdc2a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a35ea484d96c275a286f18b5abc17183b9b07710"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "38db810b4489c375f19b9a154cbb274918579797fcfc4f74160b832d56e1af4a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91b266917a813ed63532911bc03380134c5abb46"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0c0e3b08b948090bd18529bdb14ebb6576bb365ebf372eb330b1558c3242cd66"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "838cb97b1f9fe3f87751cc6946dd8a457262190b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5116c2db4e54504c424f4b825835bea82903393b2a6f02e1d29ae358197c36d0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e94e6fd7eb3e090f1c93578b866b56dae849cdf0"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6876c0d73b4f5ae06f2cec45a1709194c582aa17edafa64e9ac880b6e49b9ec1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "edbc2f1b29bb272350d2069e5a40e5c5b628c26d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e42df2b380f3787796a41cdcd581454fdb7ba7ebc3983f1042a87884ef94f82a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "235cc4f4809e9d34f3847cf3644bd5550a4b09d1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c80b715fa85010c7a8581c6267bb2990bf7bf361f09fcf4ebdd903b56351a2e8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "12fc251d38128266813d44a3f40e45e83c2fd6ea"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "9bd7998ec8cc9cac008639832593ed6cf5b77607cef1c84b4afa989e2caedf67"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d554047cce03bb4335316393644afdbd6dd7143"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7e3cabe080962afdd54c35ebdb1a84fbd261597637056bce04f59c85561afd8c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f1c6e320e1831a3180060bbf600120ba61f2aea"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2ad71169b71e7c49d34ce5404c26fe37a181aa608626823b28db5bce01bc055d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69f1835672eda1709eb656d1f7d63d6d2e173ec3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4be19641b813ef151faccca7756c4262ea95f52067e7f522f017bd9e49d826eb"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5b81a8310a01f5e2f0a26bf1dbf2735201868b6"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "52945e0e84a4bddf0760dec5128e8ee89d8291e3dad9517dd43c2acb9a130a4f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "7dfa9dbc96bd8920324df8befc146162cbafe4cd"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "ab3783c8b751558683a395660909f551875a0e2238ac44cb6db8edb125fa9572"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.10.3+0/libsingular_julia.v0.10.3.x86_64-unknown-freebsd.tar.gz"
