[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0763ce38b5f19460195bebf369fb1d930279de9d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "847f8697ca223aa3e5b3b62ecbc3fb6ca35a11e94eedfdaccd104ef32aa061b2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "851aad019a87631f27949564ff9c333bc7216d03"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "667074bd6875743ad42b4c07143bf1ef239bbd0ef933ee010aaa8fedc2fc0773"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0d8172cc66b17aee9b991de3ff38af56124125f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "be2d9d80aaa32436696a5a2061d67c64708780b64ff8220a74637fd50295ef41"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ff8cbdcea27f18fb07f624b2591afc7f46fb96a"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "361716adfe128b16427eb737b3342fc1dc159cc14bf2b4f75ed1833efd852486"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0006ca477eae9ef7104dbfa080eb91c202b30272"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "652f8a2c4992f87c10705f32d13ba4abb529d73d6b5fd9077dc0e280129f3979"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9c1cb7f03aab3deb6b477acad60ee2472e129ad"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "94deb63e77796c7b0aff86ed2cde872d8a345c67dc0ae2b75d039aecb3190bc4"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d461770b4fd643767c7e14f4be3941183ac95aa"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3cd5ced753c027665b7e6414c29c5dc64e71002fdd6647fabffb0b8acae9c195"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6094095027442bdacbeb48df8362d5246039a0fe"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "044d42856816c18221516369a66d01d865ba64ad00b6b19b15fac59e4d57ab7d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff0583c906ed5e0d09668ee1151eceed20001bcb"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "197c658772c05766802bbacd9971c2a8c99d388956b27e75132131f857cc149e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6af802463255a51a2f44a0a9e40a4fed4cb7972"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9394fbfd4ec1057b457e5698fca85e5eb3facca47894f9de4f2762bde63fbdd8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9aa75888f02325ed445d751682acd8181a1af2d3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "98a27a854631a070551e50aad78292577e76fda477d4aa20c071fb5189012ecc"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6093bb6adfc51431dac835ad1f683770b18237c4"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "84804e98025ff296d5b9bbb039a01373c621a4b7714ece686aca80f473c61c88"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "a72af423c6e22671e19cea416f7dd019bbb31152"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "4f4834044cf72c2b5094f901ba0a6bd5fb6dc58d7a16b46bce26b873c7a94718"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f666b866889ac7ea2c4dd4528504ccfd56bec99"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1d26b4746a515bfcc80a3ee8ee9ca27ced2d85d4cbe43ebc5fdafabaf1614873"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "757dd7f6fec5a68e6ab002c5b3d376d965c6c5c2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "137d17b21b30215520aa7f304f98e365eb572a8be9458df5dbe6243a67a1183d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "615f804cb092723b37f61c2da5789bee076660da"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "633f97762bc12b3fe7a539fd463b1e866e7d9bc1bab707484cc45e0f8147a6c2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8405967c0489a385b7f07ed323b033d247de88c"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9b3ee3648e83474be3c7ce84a79ec850fca74f6daa5da5aeee4f2041d5ff7224"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "860b66ceca5b0f4c28e4c6bb21c4e1cdd0fc7b59"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "b83d13e880bd7dcb1adde1bd64195130d6c8dc56144c2cd303051a2ae751db87"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.4+0/libsingular_julia.v0.9.4.x86_64-unknown-freebsd.tar.gz"
