[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21ad246d3c1239c99e2be7c4fc1ca0009300e80c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3a0d2209f2dd01fa7742a14acdc9a72787157acaeeb450c325381ca61f0d3967"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84aeaab3b81ef27df48abc2fc5bbcfe88aa9aec8"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "81517fab246641c93fb9f2dcd3894952cf25e342c125405c85a244659e45035a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c25c252dc27daa62d24fcb621c97ef6aa3a4eb7a"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "057717e412121fff690c36861227d152544b2e9a148fd7985d4c0e524b7e066a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fbd688b636ef54be2005dcb8dfffd8e49fbe137"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e032a0c6828ffe238a733c97db1b707fa11d6a3a51358853c2dbaed5c116a61d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7860d7aaa7666035315b778e239e847400f9e4f6"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6441ac4594dcbc8e5c083f1661aab489fd0f8516cd078f78c16820750a11f805"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fca33209f149ad1fe45318bce1c9503d49a5d0d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d63ce77a06028d277700ae3251dedfb7ebe8aa964544ed5399d70399116d7dc4"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de1951e8a614a6ff95c4f50e10007614235c926b"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e864482eef9b55893b80be738f8ece10056eddeb167c034e8d83a60b681201a7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fefc5bfdf52e5e0fd286181a109f8d1947db4a40"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "34184d4486d8f5719e9cb5a9a520a847bcd6d0c038c53973b7cffe9434f4e9c3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "861055ea07918630e913692723943d466e5b9998"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5f8e5b36ce2ea6ee925e91ecd8f83fc8fe01fa7eb97bbdcac06916a56a524f29"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95fd7d4402fcbd01ff014dffa2758fc553c51abb"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "305d6a8992b9e6b103950c4758ca1d04b5b3ff7fb534fcba20dc90ea4cab80c3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11383014943b1a34d261722015e27e55d7d31778"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "dae1cdd207fcc71b20df47f52681ca2d04542212e74089682619951cbc4d7ff7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6809c56e9fe90747cc9c2269376fe6526fbd0ae1"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "39f385bc67275abc18a9176d0b8294e4f719084a29afee579233123dd9a39d22"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "75a9925c281c6c857159b9e868b2c1fc260e1754"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "5880c85573d585c18d6f3a0ef3ff75fcf505b41892d586c88cc2c03d9af2c248"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24758c6228f525d20bcde45f3ac3a805ad50ece9"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "dea5b7ec546f602fe283e7a542488e9f70f2592f9218dba63a3d1ecb63f21414"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea83c84716f3c3f0214f8aa4dd14f900ff994620"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a5924abc1cdc02da18965734c9a1a3fb952431d4d9527a57f57ff87602f9b0bd"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ca5344bd7e29ba006c94d18ca7616a76fe24d16"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b1aaef4cd8d961be20cb4c61ad7dddff2d0d132162c0e5e0a13a157d7a1e9d24"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbd0e7b96903417c8e6b7ab691ed4c3f28528242"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0ebdbb823a7ffc4d800593e063ebde8ab1b79efaeec4c0fd6d715af6a99402ed"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "c1223be2e02b46cf94cff441352421eca4589c0e"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "effbd6fc9f8143d91fffa2f4e78b3aa6b3962abdce71a6e1a6129ca9700493fd"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.16.5+0/libsingular_julia.v0.16.5.x86_64-unknown-freebsd.tar.gz"
