[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86433fefde07ff81e045e995c1adb16151bedd44"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "d3181daf706b939a420eae2baf323051db70fa8ffb95c26252f3165f8538b278"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.2.0+0/libsingular_julia.v0.2.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a12411f54cb03300657220c41c350a036d63753"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "dd02507fa4d636de28e2d75feabdabd049d563d59538ad838d8a0f135b87c9a8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.2.0+0/libsingular_julia.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
