[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba0c27db8fa6c23afd7b32b2d61197c3c920951f"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "af3b5db92ba1aa9a634479569c3a553ce3be8cbd293347bbbdc8e91a5f3d666a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f08b83ba6ca147900798ad683e2b81402913eb81"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ad7b658b0309dabffa5f562f286307e47d226a361fa4667a80796dda61a2567c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d20221ac26a609d234696ca4eae2731a2494408"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0c8cc817da83fcfe05221c0ddf616d9919c2c1af6e455871acf16b2c8a3bd314"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68d8f75db8d039e6be33724c7733e6b53f2926a4"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a12f1e29cd92212521dbbe350e7b74c40c787a031b6f7bb0f0afc6f202ebff42"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50ff849c3c9b05ecb60dca48e41a512dd39910cc"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "49c25de118e63c5a637c0ecf5fbb48f842dc44a327c85337973449d337c29ba8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af2691fad56acc9eb441e23dda662fad30cf0552"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7a49873f07fa5626cefbe1f98b41924c5a4fa23cdcc539f863520d03c55ee0ec"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afdf41a669513f6886013c1f135419c9b621bc55"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e23183bd0c846236ec477b45de60303cfee9bd01e0c7a6e23ed788eeeefd8d8e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "347bd012cb58d1730a51648ebb2fadfbb7417814"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7176f7047f4fc5edec41913ac08b4772230a1d053b6bc19bc8b320c7f30f8212"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "625871c2ea0da8fa24544355e1435043560ce4d3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "67e3a73d8a8bc13524d43f90f8ed419a59938bcca2268ce74881b8e3f4d36bb5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f780b95cb0ce816f18fd95fc0895518028697c7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "bbc3a98406ef2a7844cd2a8a9f973d4a257e4749285d1efc62b6970bc7b94dc1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21b56d624aab3978c11abdc53341a9f3706ba617"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1afe244414ec09684c9c38cff83baa9aa5395eb5ec152f47e6869132778a1144"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05ff00aae8cd57b4bafe7ed9ad7315d2069de94a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2573cc8e34fe507f44376af6f8a0f7f9c445689ead21c20aaa42483bc8150fe7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "f28b82840ce84db02a30ca4006da2e6232d0ed11"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "27689fc8564f34bfe7995de7c7224a52b63fcc7c3d24cf3bb169750d33a1fbb7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d2296aac10e173d3dba726d7826fea6c247535a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4c5aca86fa28aa0dcce4677d5b61333278b74b779edc47ad956246f2ec20849b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ef4549a30d2b0a17367b63ed11aaffec6eff5ae"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6dc7de14a905c204d2a9a590e429b88ea03af966bf994799c585e2d6b021c4d8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a92d43c4d7bb3571448b056e20033ed090f30b25"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7639fc7933eca3f0a120d3fa9b2df7fe7dc362ef06d0fa771b5658091ea601f8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "589813c69d2593880952de450f372b56b4a2f862"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c574e7d72608746c52a0a5b46f60c6d4c411c56901b693ddd55445bc663f49da"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "43d3e7687cb45e902ac72763012ee91f9bc77a56"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "a01a6759214f402b0cb9c9387cc077a6ced1b795042038d06e388051671bfd40"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.14.7+0/libsingular_julia.v0.14.7.x86_64-unknown-freebsd.tar.gz"
