[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61de340dc2442ab7c348add96e06bfbc2181a571"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "bb9593f9f6689167bf15cb9a04f2e51f77612b3e170763e2d45d265faa790429"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6179e326b50e47e1bcf0823944a90e854c38395"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "142601a5e4cbea4173a2fa4d3d260177bfecac1d573ef2c0b293165fe6abea0d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82ccd064d1dcadca426efec3df2b80231bcffa22"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8c77fec9e065b4048d7a9baa397ae8107e683fde1362f7f102d9fb0d6bfbdb95"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62aa4aed21f360d03b51401d6be46a62845415c0"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6754c08f9ba812c827a82d20af12280fe2b5898e27b7d553dd7e3d91ff988c4d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc96fd8ce3bfb169cdb8f3914029c7a15de75777"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "93fda15f63844f6d56ec57593ee51cc8d99e48a8a30240c02ce01f825b53b81c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb019d65a8c2310e318d7dab8159e9cdf3988e97"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d88c60a7cb412152f5040051f3f31b2584e1e4c392c957e02401ac2afb8c4ebf"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c20016e2c8c6487c0a74a1b0541c77968f715c14"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2cb3cd70ed6897c3104ed58e5b4171e4c2bd5a71efd1b9b62358983f5f120f5b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b6365c2c7039d0022974ebb3b1d32911189f80c"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "edf4c8aee56108d92e5115d26e34e006fded56277f819310dc37a5be048cbe65"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84f2ae3cce205358896955c23aa6b6c39778220e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c9514381a4edbeb212454e70b886c69abdca008e90587e37b7abc3870c87a3b1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1ed668f2ba0761a97426b7afb7d64706f3bb023"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1f16b148cb34768e248c01146718824ffcd3650cd5cb9683760b91ef010df850"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60db3831a81b9b558822f1cb3b98912d7766b65e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d6126234457d5691293cbb19d2fdec03d81a8b0d90817607107b0b3746f81e49"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0178fb9b2a8aff2e22b91002faae257d386beeb9"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "95cd9ad538eafb2a1b1571571b133b0e54639690d253125cc004e42d1d0bda8e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "bd6c6290b8ee7ec980ee2d42ac181d1fc5a17c7f"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "19f54b8460a1b88be9f13dcb9f90660f37f8250e3fe0fded0c7dee78735752d9"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa9b62f7c0418d73976e5db47273d0aa9de9bbea"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5d466e17fd4071e2e496921c95f0aebd74fc688e37c7476d7e72870261d64707"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f54cefb82dda507cfe42a5f7046912e5deda5399"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "072302f9c9b983e16cc377803eec793d194cd37e2ae921b74e07a91ad3490d70"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74b212d0a4ab78693cf62ed93936e5f125b99bd5"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "356b22b5a89f337cefdb00f8d95ac17b364b41f94f4ae5d0ad7252a41cf3777f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83d3dd8903ac30ab7edf66a5d57d4ee342ca5862"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "90ba1b444a945db06991e5e28579a15660dd9680d3e9f5853781070be25e6c6a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "d15c37a0ab4b82a1b6b904f1628729c726029e3f"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "e304067460c4856c5f8cd56789ac358ae9697c4dcd43d49f3b7b75c6226f1631"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.12.5+0/libsingular_julia.v0.12.5.x86_64-unknown-freebsd.tar.gz"
