[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55f6949ae418518e6d337caa8e1010ec2197a9f7"
julia_version = "1.4.2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1fbbc73f6a024920ff065ce21066dd2444b3173420523d46183337451fff703e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.aarch64-linux-gnu-cxx03-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5056a7481fbddcbfb121be8b54be530cbcbf1821"
julia_version = "1.4.2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ba5430db365c45e58cd71f82ec3cdb97f364f312a5aff446420f47b5ecae4b2a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.aarch64-linux-gnu-cxx11-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e5108e7cca6a2c4bb6ab16ade4d1593eadc549a"
julia_version = "1.4.2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "30bc8b69cf6b1fe4d1ce1b12014456ed318b0647b26d98f6f12d61b4f7f6c780"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.aarch64-linux-musl-cxx03-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5044f4b2f4d329a32a2618e8c100008783bd8e99"
julia_version = "1.4.2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6ecaceebeb4bf09a9c9e8613b34263fcc25f58253c0591bcfc6d65ccd27833f1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.aarch64-linux-musl-cxx11-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "472c364e6d47502ef6223b1f8cc33c660367edb1"
julia_version = "1.4.2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "31bd4b52232e227fdc82e38970e3b58112884e87942c66b4609ee6a9365d02e8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.armv7l-linux-gnueabihf-cxx03-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8da0e24ed72792bdf5e851f43e2889da414d5d7b"
julia_version = "1.4.2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f0d46d094c1454413d801cc0505fa3178ac5c2388212a9e7c768d965a7579b2c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.armv7l-linux-gnueabihf-cxx11-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f3457b5606ad57a44bf591d89420c6afda7912c"
julia_version = "1.4.2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f6b40369f59d74329353df0de7c23f55ea0503b9cf1a406358ec604761c03a39"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.armv7l-linux-musleabihf-cxx03-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6e7b4eaedb0155ed892bfaaec282dba1c3f6697"
julia_version = "1.4.2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "9697724a690dcefa7a861083ca3881394087cb081911ea1d7ce4f007010ce9e1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.armv7l-linux-musleabihf-cxx11-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9d342da715f8b0916a01896e3796ce07bdb4f53"
julia_version = "1.4.2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "752e2545479b984f9068b7c686736a01314dcc72ba33e5853a648b2198a69ea4"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.i686-linux-gnu-cxx03-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f2db798505130dfe97b7684ad423ff3f7c1dcd2"
julia_version = "1.4.2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2c7148fb573d4efe437aec2b72aa92fdaee9b2ac88fa1414b5e3cea92ec87f27"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.i686-linux-gnu-cxx11-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0bf66cab2bbed7f89188482a0288137dcca9b3a"
julia_version = "1.4.2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b308f0f39cc23db93960a165857a5b165515bfee632df30c4411a235eb730d48"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.powerpc64le-linux-gnu-cxx03-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3171a282187b440bb937cb00678e75f19c6e9c51"
julia_version = "1.4.2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "5dc8842006f3e20f96fe694b36578da1cf65d6770555c8193fa3f8cada7e68f7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.powerpc64le-linux-gnu-cxx11-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "477d46c4a1b246b69eafddf5417fe77fb769e796"
julia_version = "1.4.2"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "79e7ed967b1175a3239f5125de9ef734a954afa12c8996e116efc4a0fcb3c82b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.x86_64-apple-darwin-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b5086b7ec20be278fabeedfacf4de46d69da576d"
julia_version = "1.4.2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "96b08c5d31df27d4a3fa05ded0265b7bf3c874eca1a058ad912798437fde446f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.x86_64-linux-gnu-cxx03-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92e4e4e1507042362da3776a015520193de7771c"
julia_version = "1.4.2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "77bca77449052f07ca6d500dda4fdda5d992b5795012f1677a1e70bc383f570b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.x86_64-linux-gnu-cxx11-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b94ffb6146d7be298eaaa2193de2a7da9d5c7c48"
julia_version = "1.4.2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8ab463bab8aa7f6902703fa9a1df46b646740a62d234ac944b6a770862c7adce"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.x86_64-linux-musl-cxx03-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b34f2653355b0d65ea2ee3fedafe9f38d4992dcb"
julia_version = "1.4.2"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b7c7c451caa431e610b28a4f7c5dca871fb5a8fc572b6ab6975490d83bd6ec82"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.x86_64-linux-musl-cxx11-julia_version+1.4.2.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "d2960b016d8771dfc158fdc53666a0ee3edb0894"
julia_version = "1.4.2"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "1d52fb398be015ce5d287adaa13c27d9928331bd44fc5e50a355d233be77a3b3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.18.4+0/libsingular_julia.v0.18.4.x86_64-unknown-freebsd-julia_version+1.4.2.tar.gz"
