[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47f41fe56a986a30d5ae255c749532e1bdc52ea2"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "a912f12dbf8693a797abb611acc35531d13a93dbabab037975c071914dc5a043"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f59090260de5acea6656f3f682b002df33a17e7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "bc7f7535ff0b4154eb3b136e42f59aade2889af98c5a144cd27c08ecac74e6b4"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d586ba60df66eb44586965237796002ed2414b72"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ef83d0066c42472f3b896dc9751340f91534349cf34094a101797258c6708c49"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4b641e850a58456e298a3f08fcce07a9310d74f"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8481533bc815684b6fb918db2fc3132fcfa16c4358dd7a122df5a3b9f4454806"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c6fa7e887b617abeb1336d4d6c76da75c52b2fb"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "0128094e9a858225c0509992a58c4abee97d48ad906d3f5902e872b428a9f432"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccd9ce26c4cc6c0062a3c244ff308f8d23dfd867"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e6cb47a2ca6924756fb87aa11877774e2003533845f27393baf43db306da6302"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3fbeb254203d5d45bf52880c874c148506d40a8"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "736a2788406fee170687d8aa3f1540f083929d23c5cebec596e0a3ac9ba61b2b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1e345169147c76f8b4dad6a33bf0c9ad60cee61"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "8c1c4f7b01a6f8115da1c552a265d801341a56f2fdb24dd6396209364d0b9a9c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d4c014c0e18d9e687db6fe8f98a67ecf9992d47"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "70a58a8117a34bf4c0a78e5a8a820317e76c170a4f3669806f8b5ebd6e945301"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a08c9e90af2012edfdefd9c637123a886f734a7"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "fe5232fc7035cec7834d101136367ad34f3a1b42c420829543aceb060733e60d"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "954a2a6da77cce6f7d60eca50385f604f7f0c966"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "dd332991e001e5b06da2baee8eb0d6a753d496ac12e2e01beea57248a572f0fc"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9d489ca829985bddad369b814d24fe7b8a08b9b"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b854974c4f25c933952984141791340edfa2e795f82a2e3463cbf9b2d07519a1"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "7e3d98fd5924a284a57aac01f71e53118b3ea278"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "ed401993a0890cfba8a66cfe20f572da19a2be45207a9b51dae68266e484f171"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3206d2ef2af0cdc03fed63c7e722e1e839283b5d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "6a9e77786b37770f2602d2a86443887b1a40774aeb5236a724e353d6744c3689"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bab24efbce87c550e92a418c4ff328d76abeeb4"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e9d5bc2460c6d7b4a4c6bdf46d34644acf9f137535eade71130d074b377d850c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf056b4768094e3cff71370dbc05ddd187d922af"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "948b583e5e7d665c3aeecc1fbc0aea52fd59cce159348ed6985b9be5a75c0e21"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45b4f9fb8444a62c0e175ecefbc3563e1cf32769"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c1fdcd504595339323c54916868921412b1dfda107560153ebe5a954245e608f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "c273658dcc24078e104d5af59871dc08f372869f"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "93f589fabd11b1e92d6898191f7f660277aaa2ccc23e53c6b5731ea44957ea23"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.6.4+0/libsingular_julia.v0.6.4.x86_64-unknown-freebsd.tar.gz"
