[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d42a4e68acf9fd818fcde26aa7dbd79e8e7738c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e8587e52eadb3d07259421719ed9888587c185ae57f228240f76bd28f075d412"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "221d97f210c6f7d796bd001d75de9dd058ca33b0"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1d07079053b07923865bb3f67ee203d4e342c4467da2ead8e37a81c91af9637f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c9ce90183444bef1d8ffefa365aa4f4cf9aa8e7"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "f69daa1e69f18664a9a74952ea0a44ce51c5c58c4cde41a30a46431b3092e873"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a626402baae270a7595ef3026fe889e7ac1bfc0"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "ee0c1ae49d2740f4a6a13fc88da16e80f50a32f9e4e52977a4b821bfaf69eb92"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f33ccc214309ce6b29b5c90ab860aabb6b8fbbc0"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "59d2c0ca7a3c39b2219160a74aff8d8f58cfc3a1d7c601d7d1fc670a23eb5ba2"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14c90a0a82b666a0944cdf7b40f5ee5cc323b621"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "dc612c992bd57052cd734e7d9edc41be1817daf3aa3c383c15d2a41c705df4b8"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bba1e0c44597cdaa0e10c76ae12cbe4f8669622"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "723cd802d40f4a6754c9868f341aae5aac99c3dd0995e90b306197cd8c5a8495"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cd6dc528e482565d01ae479338986107d3179ae"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "20a6a90eebff129c20ecd49b246013019c76eac37be18309070a48a53efcd8f0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c77b4a5822012405d0cc6b3a3a2a109003e7ca5"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c81c54382e047638c88a3812a82d240cc419ba857ebc7a9b072bd24454b29007"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3849597e7d0ea29b99dbf6c24a9a79c655c63e8d"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "313f26110f6b76a96f9ac9f1f3e5f8643b8e1d63d8ba91f00970bedeb532da21"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f293eca37aef6677b2cf9f0609cdae8d0ed8ce38"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2735f636876188aa04251204b2709d751a1698f27e88a05f708ce3288826a3f3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd3cf312d852ba66bd806ebd3121f0cae8257bdc"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "582e87d226106c55fe3e8481b5085278fc8a4071f729702a5dfc00e328cd6b9b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "845792f258701bd2aeff392a918424a627972d4c"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "38d4af16dd13f3b9811a818191f358daf436f612ad44189b6f4e5fcc76c684ca"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a83b3c6b91b3cec16ec31ac5f52fb465246ae35e"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "7ee66df8df7a00111272301475485d0b58c312e4228dc99b086bc7a987e28c64"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a37ba09ee70bce98adda5cd3cb664ebac3d7fb0c"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "209d56e704b2e00ca370ef32aa6e60e3c2af6fb2d6f00f1200490ecb57a5f1b0"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0cb3fe73e3fc8e7cea76ebb6200a29b488860730"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "c45db1f6cfdfc6f541b38ff9cb73d4cd8092ab92640bff16cfce292d50e7941c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "369dd9d6897c8393dc28c18eaa2f78853a56ccd8"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "1c393e0ff9275cc2a64022da4a2efbfbeec2fd840146a100322a1b7c53867e29"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "b8b8706ee7656357107ee775059f3afa49f5fc83"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "6cfe97fcf6019a24f999b5fce1835fb8f68699b2e4dda57825d3c30a5cc47788"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.17.5+0/libsingular_julia.v0.17.5.x86_64-unknown-freebsd.tar.gz"
