[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a53817bac8013b95899a43ba0757261a9fe58bd"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "751e4876b6c262efb7c710351896f50252aba2cdb98a2a38c1eb8321e55341c5"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.aarch64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5480860f5c37aa893d6c8e0171fbed1fc248a887"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "01ffae00827feef40668ad8c50bdf46bcb4d174ab740c49f7a9bd05a9651cdfc"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.aarch64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7bb8dc997bb74641db15908485c6865eace0695"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "50c97d36b756b7fa2a189e7d6cf4c7d3dfb9a026338508110ad64422d8e6d30a"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.aarch64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "532a35837e1dbd7ffa46144c2c093f4be0fd507d"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "cfaa4bf9fc90efdbf1a06e8fce6d3f45281a6a89437e19e71c486c8e4232204c"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.aarch64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1210b2e07f94c60e717e68115ad28efd2389e2bd"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "e396d6dfacc44896a7147e36ae56354cb410c054d48fd706e19ac4396beeb2b7"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ddff0f0bdadeacf12628020ec33103d380a694a"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "b01e7b62fcf0d75bf83ab07d16a5aa7a480e54b623b7d6cba7b2ae3c44ea525f"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd60e127b7257e3e877cd7443f1e12dd06467ca9"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "3e01c606f2297ccdb899417a3a537ed14ef320bc25893876924db2ca74c25b98"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsingular_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2618def7cadac3997b7aa46858612ee8e3550adc"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "d51ef0f3125a32866f1c1fd87e48a151fac316611cc4e0405c41d062caa62e8e"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fff1bc15243dc3afbb980f8b3f7f7e44fac8b198"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "80813bfcbf9743e726277c09507f50967c574d38d314dbab976c8bc4558bd617"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.i686-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0eefb9f58f6f17142efb162b76828a27680d24b"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "2f7ae02fdaf1126fb285c06d08d155fcb457afa2e3268c32b154ac5fa06395a3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.i686-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3bb6539fc6b2d6f0a82428c08796d3d78b86d25"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "eff7fe226a42c8bda1a4fb49fd34f82621704acc99195943bb8b94122c05bd32"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35252de8545b51a395f796ee6c590900cdf0ece3"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "4b1f0bfa294ff28686f8bdee7eb5afe513058b2ed050639b051d60aaf932f01b"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "ba184dbd5af604b5d47b8b71e83efbf3bba4317d"
os = "macos"

    [[libsingular_julia.download]]
    sha256 = "e5558e2834fc260a4809a799e52a30e8b0c8fdcf57b6cd15f0ec9ef8e4154036"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.x86_64-apple-darwin.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f96f30fcab8347bffccd989fe042819f799896cb"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "be33de06de689b73dd4736b46e3fd17752e4e3ee5f71920ae4f1acd6b9d2a4b3"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.x86_64-linux-gnu-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88f35a35a2aa71e5562d247d7c274efd12acfcb9"
libc = "glibc"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "abbdb013f7da4c57a480ae501f628db6088fae12409d700d2901ff113a3b9962"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.x86_64-linux-gnu-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9529bfb379eda96cddecf652d4e49f656ccc4956"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "962664841fbaa2664671299d7c73a6722d14d8cb5420bd5e9013cd0739a37580"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.x86_64-linux-musl-cxx03.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ac1cf80e623470d2185f8af7b164491d5edc2a3"
libc = "musl"
os = "linux"

    [[libsingular_julia.download]]
    sha256 = "dfee28d591f03b659898fdfef27ad91382a12592b406c2d0432034568b2ba735"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.x86_64-linux-musl-cxx11.tar.gz"
[[libsingular_julia]]
arch = "x86_64"
git-tree-sha1 = "f6f2bcf98e37aec0243946ab5ae64b27fda73d11"
os = "freebsd"

    [[libsingular_julia.download]]
    sha256 = "80b1a74178f7854af32290c759b4eea7ca8e43a3be905bfcc8bbdebec04e0ffd"
    url = "https://github.com/JuliaBinaryWrappers/libsingular_julia_jll.jl/releases/download/libsingular_julia-v0.9.205+0/libsingular_julia.v0.9.205.x86_64-unknown-freebsd.tar.gz"
